using System;
using System.Collections.Generic;

namespace Traceability_System.Entity.Model
{
    public partial class RotorTable
    {
        public int Id { get; set; }
        public string? InterNo { get; set; }
        public string? CaseDec { get; set; }
        public string? RrCoverDec { get; set; }
        public string? ParkingDec { get; set; }
        public string? GearDec { get; set; }
        public string? DefLingDec { get; set; }
        public string? HsgDec { get; set; }
        public string? Mg1statorDec { get; set; }
        public string? Mg2statorDec { get; set; }
        public string? Mg1rotorDec { get; set; }
        public string? Mg2rotorDec { get; set; }
        public string? LineDec { get; set; }
        public string? Dfcase { get; set; }
        public string? OilPump { get; set; }
        public string? CaseSerial { get; set; }
        public string? HsgSerial { get; set; }
        public string? Mg1sserial { get; set; }
        public string? Mg2sserial { get; set; }
        public string? Mg1rserial { get; set; }
        public string? Mg2rserial { get; set; }
        public string? CoDriveSerial { get; set; }
        public string? MoDriveSerial { get; set; }
        public string? DrivenSerial { get; set; }
        public string? DorpinSerial { get; set; }
        public string? DfringSerial { get; set; }
        public string? DfcaseSerial { get; set; }
        public string? RrcoverSerial { get; set; }
        public string? ShipmentSerial { get; set; }
        public string? RropSerial { get; set; }
        public string? RotorShaftTrans { get; set; }
        public string? RotorCoreTrans { get; set; }
        public string? RotorHeating { get; set; }
        public string? RotorShaftPress { get; set; }
        public string? RotorNutTight { get; set; }
        public string? RotorForeignSuction { get; set; }
        public string? RotorNutCrimpMg1press { get; set; }
        public string? RotorResolverPress { get; set; }
        public string? RotorReject { get; set; }
        public string? RotorMagnetization { get; set; }
        public string? RotorExtractionInsp { get; set; }
        public string? RotorShippingInsp { get; set; }
        public string? RotorTamg2shaftTrans { get; set; }
        public string? RotorTamg2coreTrans { get; set; }
        public string? RotorTamg2heating { get; set; }
        public string? RotorTamg2shaftPress { get; set; }
        public string? RotorTamg2nutTight { get; set; }
        public string? RotorTamg2foreignSuction { get; set; }
        public string? RotorTamg2nutCrimpMg1press { get; set; }
        public string? RotorTamg2resolverPress { get; set; }
        public string? RotorTamg2reject { get; set; }
        public string? RotorTamg2magnetization { get; set; }
        public string? RotorTamg2extractionInsp { get; set; }
        public string? RotorTamg2shippingInsp { get; set; }
        public string? MotorMtrCode { get; set; }
        public string? MotorSngen { get; set; }
        public string? MotorHsgSrfBrgAm { get; set; }
        public string? MotorHsgSrfKnockPam { get; set; }
        public string? MotorCoolPipeMw { get; set; }
        public string? MotorTermBoardMw { get; set; }
        public string? MotorRrCoverSrfOutBrgAm { get; set; }
        public string? MotorRrCoverSrfKnockPam { get; set; }
        public string? MotorMg1statorInsAm { get; set; }
        public string? MotorMg2statorInsAm { get; set; }
        public string? MotorHarnEscMw { get; set; }
        public string? MotorMg12statorTightAm { get; set; }
        public string? MotorThermMw { get; set; }
        public string? MotorCoolPipeMw2 { get; set; }
        public string? MotorMg12rotorAssem { get; set; }
        public string? MotorFipgapp { get; set; }
        public string? MotorRrCoverAssem { get; set; }
        public string? MotorRrCoverTight1 { get; set; }
        public string? MotorRrCoverTight2 { get; set; }
        public string? MotorInvMw { get; set; }
        public string? MotorMw1 { get; set; }
        public string? MotorMw2 { get; set; }
        public string? MotorPrevStn { get; set; }
        public string? MotorMwco0 { get; set; }
        public string? MotorMwco1 { get; set; }
        public string? MotorMwco2 { get; set; }
        public string? MotorMwco3 { get; set; }
        public string? MotorReject { get; set; }
        public string? CoverSubIdsetSpare { get; set; }
        public string? CoverSubRrCovSetDmread { get; set; }
        public string? CoverSubRrCovBrgPressEquip { get; set; }
        public string? CoverSubMw1 { get; set; }
        public string? CoverSubMw2 { get; set; }
        public string? CoverSubMw3 { get; set; }
        public string? CoverSubMw4 { get; set; }
        public string? CoverSubRrRevEquip { get; set; }
        public string? CoverSubWaterConnTighten { get; set; }
        public string? CoverSubReject { get; set; }
        public string? DefDfcaseRead { get; set; }
        public string? DefDfpinionShaftEquip { get; set; }
        public string? DefDiffOperMeasureEquip { get; set; }
        public string? DefTweezersMw { get; set; }
        public string? DefDiffPinionPress { get; set; }
        public string? Dmread { get; set; }
        public string? GearPressIn1 { get; set; }
        public string? GearPressIn2 { get; set; }
        public string? Slnffastening { get; set; }
        public string? Slnfriveting { get; set; }
        public string? DiffBrgPressIn { get; set; }
        public string? DiffBoltTight1 { get; set; }
        public string? DiffBoltTight2 { get; set; }
        public string? RevRivetConfirm { get; set; }
        public string? DamperImage { get; set; }
        public string? Reject { get; set; }
        public string? Idwrite { get; set; }
        public string? HsgSubShimSel { get; set; }
        public string? HsgBrgPressIn1 { get; set; }
        public string? HsgBrgPressIn2 { get; set; }
        public string? GearAssembly1 { get; set; }
        public string? OilPumpAssembly { get; set; }
        public string? SubShimSel { get; set; }
        public string? ShimSet { get; set; }
        public string? LubPipeAssem { get; set; }
        public string? CaseFipgapp { get; set; }
        public string? AssemJoining1 { get; set; }
        public string? AssemTight1 { get; set; }
        public string? AssemTight2 { get; set; }
        public string? DrainPlugTight { get; set; }
        public string? DiffOilsealPress1 { get; set; }
        public string? DiffOilsealPress2 { get; set; }
        public string? FillerTight { get; set; }
        public string? AssyUpright { get; set; }
        public string? Idexchange { get; set; }
        public string? OilCoolerAssem { get; set; }
        public string? MandrelAttach { get; set; }
        public string? Preprocessing { get; set; }
        public string? AssyLeakTest { get; set; }
        public string? Insulation { get; set; }
        public string? OilInjection { get; set; }
        public string? AssyNoiseTest { get; set; }
        public string? Mw1 { get; set; }
        public string? Mw2 { get; set; }
        public string? Mw3 { get; set; }
        public string? SerialStamping { get; set; }
        public string? ShippingPrep1 { get; set; }
        public string? ShippingPrep2 { get; set; }
        public string? VisualInsp { get; set; }
        public string? Fipgreject { get; set; }
        public string? LabelPrinting { get; set; }
        public string? Reshuffle { get; set; }
        public string? PokayokeDate39 { get; set; }
        public string? PokayokeDate40 { get; set; }
        public string? HsgBrgMeasDate { get; set; }
        public string? HsgBrgInflectPtStroke { get; set; }
        public string? HsgBrgInflectPtLoad { get; set; }
        public string? HsgBrgFinalStroke { get; set; }
        public string? HsgBrgFinalLoad { get; set; }
        public string? HsgBrgInflectPtStrokeSec { get; set; }
        public string? HsgBrgInflectPtLoadSec { get; set; }
        public string? HsgBrgFinalStrokeSec { get; set; }
        public string? HsgBrgFinalLoadSec { get; set; }
        public string? HsgBrgMaasterStroke { get; set; }
        public string? PokayokeDate41 { get; set; }
        public string? PokayokeDate42 { get; set; }
        public string? PokayokeDate43 { get; set; }
        public string? PokayokeDate44 { get; set; }
        public string? UpenderDate { get; set; }
        public string? PokayokeDate45 { get; set; }
        public string? RejectTime { get; set; }
        public string? PokayokeDate33 { get; set; }
        public string? DgameasDate { get; set; }
        public string? Dgapos3Axis { get; set; }
        public string? Dgaload3Axis { get; set; }
        public string? Dgapos4Axis { get; set; }
        public string? Dgaload4Axis { get; set; }
        public string? PokayokeDate34 { get; set; }
        public string? DgmmeasTime { get; set; }
        public string? Dgmdagjudge { get; set; }
        public string? DgmlhRh { get; set; }
        public string? DgmmaxTorque { get; set; }
        public string? DgmminTorque { get; set; }
        public string? DprmeasTime { get; set; }
        public string? Dprfrs { get; set; }
        public string? Dprfrl { get; set; }
        public string? PokayokeDate35 { get; set; }
        public string? GearMeasDate { get; set; }
        public string? GearStroke { get; set; }
        public string? GearLoad { get; set; }
        public string? GearFinalStroke { get; set; }
        public string? GearFinalLoad { get; set; }
        public string? GearStrokeSec { get; set; }
        public string? GearLoadSec { get; set; }
        public string? GearFinalStrokeSec { get; set; }
        public string? GearFinalLoadSec { get; set; }
        public string? GearMainStroke { get; set; }
        public string? GearAbvalue { get; set; }
        public string? Gear2Date { get; set; }
        public string? Gear2Stroke { get; set; }
        public string? Gear2Load { get; set; }
        public string? Gear2FinalStroke { get; set; }
        public string? Gear2FinalLoad { get; set; }
        public string? Gear2StrokeSec { get; set; }
        public string? Gear2LoadSec { get; set; }
        public string? Gear2FinalStrokeSec { get; set; }
        public string? Gear2FinalLoadSec { get; set; }
        public string? Gear2MainStroke { get; set; }
        public string? Gear2Abvalue { get; set; }
        public string? DpntDate { get; set; }
        public string? DpntTorqueAxis1 { get; set; }
        public string? DpntAngleAxis1 { get; set; }
        public string? DpntJudgment { get; set; }
        public string? DpntSeating { get; set; }
        public string? DpntDrop { get; set; }
        public string? DpntSlack { get; set; }
        public string? DpnfMeasDate { get; set; }
        public string? DpnfFinalStroke { get; set; }
        public string? DpnfFinalLoad { get; set; }
        public string? DpnfMainStroke { get; set; }
        public string? Dfbrgdate { get; set; }
        public string? Dfbrgstroke { get; set; }
        public string? Dfbrgload { get; set; }
        public string? DfbrgfinalStroke { get; set; }
        public string? DfbrgfinalLoad { get; set; }
        public string? DfbrgstrokeSec { get; set; }
        public string? DfbrgloadSec { get; set; }
        public string? DfbrgfinalStrokeSec { get; set; }
        public string? DfbrgfinalLoadSec { get; set; }
        public string? DfbrgmainStroke { get; set; }
        public string? Df1date { get; set; }
        public string? Df1angleAxis1 { get; set; }
        public string? Df1codeAxis1 { get; set; }
        public string? Df1angleAxis2 { get; set; }
        public string? Df1codeAxis2 { get; set; }
        public string? Df1angleAxis3 { get; set; }
        public string? Df1codeAxis3 { get; set; }
        public string? Df1angleAxis4 { get; set; }
        public string? Df1codeAxis4 { get; set; }
        public string? Df1angleAxis5 { get; set; }
        public string? Df1codeAxis5 { get; set; }
        public string? Df1angleAxis6 { get; set; }
        public string? Df1codeAxis6 { get; set; }
        public string? Df1abvalue { get; set; }
        public string? Df2date { get; set; }
        public string? Df2angleAxis1 { get; set; }
        public string? Df2codeAxis1 { get; set; }
        public string? Df2angleAxis2 { get; set; }
        public string? Df2codeAxis2 { get; set; }
        public string? Df2angleAxis3 { get; set; }
        public string? Df2codeAxis3 { get; set; }
        public string? Df2angleAxis4 { get; set; }
        public string? Df2codeAxis4 { get; set; }
        public string? Df2angleAxis5 { get; set; }
        public string? Df2codeAxis5 { get; set; }
        public string? Df2angleAxis6 { get; set; }
        public string? Df2codeAxis6 { get; set; }
        public string? Df2abvalue { get; set; }
        public string? DfreverseDate { get; set; }
        public string? PokayokeDate36 { get; set; }
        public string? PokayokeDate37 { get; set; }
        public string? PokayokeDate38 { get; set; }
        public string? Mg1workTemp { get; set; }
        public string? Mg1fluxValue { get; set; }
        public string? Mg1dec { get; set; }
        public string? Mg2workTemp { get; set; }
        public string? Mg2fluxValue { get; set; }
        public string? Mg2dec { get; set; }
        public string? Asldate { get; set; }
        public string? Ictldate { get; set; }
        public string? Rcserial { get; set; }
        public string? AxisSerial { get; set; }
        public string? ProcDate { get; set; }
        public string? IsRcheat { get; set; }
        public string? HeatSt { get; set; }
        public string? HeatProcedure { get; set; }
        public string? RoomTemp { get; set; }
        public string? AxisTemp { get; set; }
        public string? CoreBefore { get; set; }
        public string? CoreAfter { get; set; }
        public string? Ihbefore { get; set; }
        public string? Ihafter { get; set; }
        public string? Cdtemp { get; set; }
        public string? HeatTime { get; set; }
        public string? HeatOutput { get; set; }
        public string? HeatEndTime { get; set; }
        public string? JudgmentCode { get; set; }
        public string? Apidate { get; set; }
        public string? Apistroke { get; set; }
        public string? Apiload { get; set; }
        public string? ApifinalStroke { get; set; }
        public string? ApimainStroke { get; set; }
        public string? ApicoreTemp { get; set; }
        public string? Apisttime { get; set; }
        public string? ApiinitTilt { get; set; }
        public string? Apipos { get; set; }
        public string? ApideviationLoad { get; set; }
        public string? Apicode { get; set; }
        public string? Apimachine { get; set; }
        public string? Ntdate { get; set; }
        public string? NttorqueAxis1 { get; set; }
        public string? NtangleAxis1 { get; set; }
        public string? Ntcode { get; set; }
        public string? Nthistory { get; set; }
        public string? Ntseating1 { get; set; }
        public string? Ntdrop1 { get; set; }
        public string? Ntslack1 { get; set; }
        public string? Rapdate { get; set; }
        public string? Rapbefore { get; set; }
        public string? Rapafter { get; set; }
        public string? Rapload { get; set; }
        public string? RapmainStroke { get; set; }
        public string? Rapcode { get; set; }
        public string? RapwashSensor { get; set; }
        public string? RapwashMain { get; set; }
        public string? RapwashPos { get; set; }
        public string? Rapstroke { get; set; }
        public string? RaploadSec { get; set; }
        public string? RapfinalStroke { get; set; }
        public string? Rapmain2Stroke { get; set; }
        public string? Rapcode2 { get; set; }
        public string? RtpstartDate { get; set; }
        public string? Rtpstroke { get; set; }
        public string? Rtpload { get; set; }
        public string? RtpfinalStroke { get; set; }
        public string? RtpmainStroke { get; set; }
        public string? Rtpcode { get; set; }
        public string? Rtphistory { get; set; }
        public string? Detection1 { get; set; }
        public string? Detection2 { get; set; }
        public DateTime? CollectionDate { get; set; }
        public int? Number { get; set; }
    }
}
