using System;
using System.Collections.Generic;

namespace Traceability_System.Entity.Model
{
    public partial class Rrtable
    {
        public int Id { get; set; }
        public string? InterNo { get; set; }
        public string? CaseDec { get; set; }
        public string? RrCoverDec { get; set; }
        public string? ParkingDec { get; set; }
        public string? GearDec { get; set; }
        public string? DefLingDec { get; set; }
        public string? HsgDec { get; set; }
        public string? Mg1statorDec { get; set; }
        public string? Mg2statorDec { get; set; }
        public string? Mg1rotorDec { get; set; }
        public string? Mg2rotorDec { get; set; }
        public string? LineDec { get; set; }
        public string? Dfcase { get; set; }
        public string? OilPump { get; set; }
        public string? CaseSerial { get; set; }
        public string? HsgSerial { get; set; }
        public string? Mg1sserial { get; set; }
        public string? Mg2sserial { get; set; }
        public string? Mg1rserial { get; set; }
        public string? Mg2rserial { get; set; }
        public string? CoDriveSerial { get; set; }
        public string? MoDriveSerial { get; set; }
        public string? DrivenSerial { get; set; }
        public string? DorpinSerial { get; set; }
        public string? DfringSerial { get; set; }
        public string? DfcaseSerial { get; set; }
        public string? RrcoverSerial { get; set; }
        public string? ShipmentSerial { get; set; }
        public string? RropSerial { get; set; }
        public string? RotorShaftTrans { get; set; }
        public string? RotorCoreTrans { get; set; }
        public string? RotorHeating { get; set; }
        public string? RotorShaftPress { get; set; }
        public string? RotorNutTight { get; set; }
        public string? RotorForeignSuction { get; set; }
        public string? RotorNutCrimpMg1press { get; set; }
        public string? RotorResolverPress { get; set; }
        public string? RotorReject { get; set; }
        public string? RotorMagnetization { get; set; }
        public string? RotorExtractionInsp { get; set; }
        public string? RotorShippingInsp { get; set; }
        public string? RotorTamg2shaftTrans { get; set; }
        public string? RotorTamg2coreTrans { get; set; }
        public string? RotorTamg2heating { get; set; }
        public string? RotorTamg2shaftPress { get; set; }
        public string? RotorTamg2nutTight { get; set; }
        public string? RotorTamg2foreignSuction { get; set; }
        public string? RotorTamg2nutCrimpMg1press { get; set; }
        public string? RotorTamg2resolverPress { get; set; }
        public string? RotorTamg2reject { get; set; }
        public string? RotorTamg2magnetization { get; set; }
        public string? RotorTamg2extractionInsp { get; set; }
        public string? RotorTamg2shippingInsp { get; set; }
        public string? MotorMtrCode { get; set; }
        public string? MotorSngen { get; set; }
        public string? MotorHsgSrfBrgAm { get; set; }
        public string? MotorHsgSrfKnockPam { get; set; }
        public string? MotorCoolPipeMw { get; set; }
        public string? MotorTermBoardMw { get; set; }
        public string? MotorRrCoverSrfOutBrgAm { get; set; }
        public string? MotorRrCoverSrfKnockPam { get; set; }
        public string? MotorMg1statorInsAm { get; set; }
        public string? MotorMg2statorInsAm { get; set; }
        public string? MotorHarnEscMw { get; set; }
        public string? MotorMg12statorTightAm { get; set; }
        public string? MotorThermMw { get; set; }
        public string? MotorCoolPipeMw2 { get; set; }
        public string? MotorMg12rotorAssem { get; set; }
        public string? MotorFipgapp { get; set; }
        public string? MotorRrCoverAssem { get; set; }
        public string? MotorRrCoverTight1 { get; set; }
        public string? MotorRrCoverTight2 { get; set; }
        public string? MotorInvMw { get; set; }
        public string? MotorMw1 { get; set; }
        public string? MotorMw2 { get; set; }
        public string? MotorPrevStn { get; set; }
        public string? MotorMwco0 { get; set; }
        public string? MotorMwco1 { get; set; }
        public string? MotorMwco2 { get; set; }
        public string? MotorMwco3 { get; set; }
        public string? MotorReject { get; set; }
        public string? CoverSubIdsetSpare { get; set; }
        public string? CoverSubRrCovSetDmread { get; set; }
        public string? CoverSubRrCovBrgPressEquip { get; set; }
        public string? CoverSubMw1 { get; set; }
        public string? CoverSubMw2 { get; set; }
        public string? CoverSubMw3 { get; set; }
        public string? CoverSubMw4 { get; set; }
        public string? CoverSubRrRevEquip { get; set; }
        public string? CoverSubWaterConnTighten { get; set; }
        public string? CoverSubReject { get; set; }
        public string? DefDfcaseRead { get; set; }
        public string? DefDfpinionShaftEquip { get; set; }
        public string? DefDiffOperMeasureEquip { get; set; }
        public string? DefTweezersMw { get; set; }
        public string? DefDiffPinionPress { get; set; }
        public string? Dmread { get; set; }
        public string? GearPressIn1 { get; set; }
        public string? GearPressIn2 { get; set; }
        public string? Slnffastening { get; set; }
        public string? Slnfriveting { get; set; }
        public string? DiffBrgPressIn { get; set; }
        public string? DiffBoltTight1 { get; set; }
        public string? DiffBoltTight2 { get; set; }
        public string? RevRivetConfirm { get; set; }
        public string? DamperImage { get; set; }
        public string? Reject { get; set; }
        public string? Idwrite { get; set; }
        public string? HsgSubShimSel { get; set; }
        public string? HsgBrgPressIn1 { get; set; }
        public string? HsgBrgPressIn2 { get; set; }
        public string? GearAssembly1 { get; set; }
        public string? OilPumpAssembly { get; set; }
        public string? SubShimSel { get; set; }
        public string? ShimSet { get; set; }
        public string? LubPipeAssem { get; set; }
        public string? CaseFipgapp { get; set; }
        public string? AssemJoining1 { get; set; }
        public string? AssemTight1 { get; set; }
        public string? AssemTight2 { get; set; }
        public string? DrainPlugTight { get; set; }
        public string? DiffOilsealPress1 { get; set; }
        public string? DiffOilsealPress2 { get; set; }
        public string? FillerTight { get; set; }
        public string? AssyUpright { get; set; }
        public string? Idexchange { get; set; }
        public string? OilCoolerAssem { get; set; }
        public string? MandrelAttach { get; set; }
        public string? Preprocessing { get; set; }
        public string? AssyLeakTest { get; set; }
        public string? Insulation { get; set; }
        public string? OilInjection { get; set; }
        public string? AssyNoiseTest { get; set; }
        public string? Mw1 { get; set; }
        public string? Mw2 { get; set; }
        public string? Mw3 { get; set; }
        public string? SerialStamping { get; set; }
        public string? ShippingPrep1 { get; set; }
        public string? ShippingPrep2 { get; set; }
        public string? VisualInsp { get; set; }
        public string? Fipgreject { get; set; }
        public string? LabelPrinting { get; set; }
        public string? Reshuffle { get; set; }
        public string? PokayokeDate39 { get; set; }
        public string? PokayokeDate40 { get; set; }
        public string? HsgBrgMdate { get; set; }
        public string? HsgBrgStroke { get; set; }
        public string? HsgBrgLoad { get; set; }
        public string? HsgBrgFinalStroke { get; set; }
        public string? HsgBrgFinalLoad { get; set; }
        public string? HsgBrgStrokeSec { get; set; }
        public string? HsgBrgLoadSec { get; set; }
        public string? HsgBrgFinalStrokeSec { get; set; }
        public string? HsgBrgFinalLoadSec { get; set; }
        public string? HsgBrgMainStroke { get; set; }
        public string? PokayokeDate41 { get; set; }
        public string? PokayokeDate42 { get; set; }
        public string? PokayokeDate43 { get; set; }
        public string? PokayokeDate44 { get; set; }
        public string? UpenderDate { get; set; }
        public string? PokayokeDate45 { get; set; }
        public string? RejectTime { get; set; }
        public DateTime? CollectionDate { get; set; }
        public string? Number { get; set; }
    }
}
