using System;
using System.Collections.Generic;

namespace Traceability_System.Entity.Model
{
    public partial class Vw2RotorTable
    {
        public string? Ro2Mg1rserial { get; set; }
        public string? Ro2PokayokeDate39 { get; set; }
        public string? Ro2PokayokeDate40 { get; set; }
        public string? Ro2HsgBrgMeasDate { get; set; }
        public string? Ro2HsgBrgInflectPtStroke { get; set; }
        public string? Ro2HsgBrgInflectPtLoad { get; set; }
        public string? Ro2HsgBrgFinalStroke { get; set; }
        public string? Ro2HsgBrgFinalLoad { get; set; }
        public string? Ro2HsgBrgInflectPtStrokeSec { get; set; }
        public string? Ro2HsgBrgInflectPtLoadSec { get; set; }
        public string? Ro2HsgBrgFinalStrokeSec { get; set; }
        public string? Ro2HsgBrgFinalLoadSec { get; set; }
        public string? Ro2HsgBrgMaasterStroke { get; set; }
        public string? Ro2PokayokeDate41 { get; set; }
        public string? Ro2PokayokeDate42 { get; set; }
        public string? Ro2PokayokeDate43 { get; set; }
        public string? Ro2PokayokeDate44 { get; set; }
        public string? Ro2UpenderDate { get; set; }
        public string? Ro2PokayokeDate45 { get; set; }
        public string? Ro2RejectTime { get; set; }
        public string? Ro2PokayokeDate33 { get; set; }
        public string? Ro2DgameasDate { get; set; }
        public string? Ro2Dgapos3Axis { get; set; }
        public string? Ro2Dgaload3Axis { get; set; }
        public string? Ro2Dgapos4Axis { get; set; }
        public string? Ro2Dgaload4Axis { get; set; }
        public string? Ro2PokayokeDate34 { get; set; }
        public string? Ro2DgmmeasTime { get; set; }
        public string? Ro2Dgmdagjudge { get; set; }
        public string? Ro2DgmlhRh { get; set; }
        public string? Ro2DgmmaxTorque { get; set; }
        public string? Ro2DgmminTorque { get; set; }
        public string? Ro2DprmeasTime { get; set; }
        public string? Ro2Dprfrs { get; set; }
        public string? Ro2Dprfrl { get; set; }
        public string? Ro2PokayokeDate35 { get; set; }
        public string? Ro2GearMeasDate { get; set; }
        public string? Ro2GearStroke { get; set; }
        public string? Ro2GearLoad { get; set; }
        public string? Ro2GearFinalStroke { get; set; }
        public string? Ro2GearFinalLoad { get; set; }
        public string? Ro2GearStrokeSec { get; set; }
        public string? Ro2GearLoadSec { get; set; }
        public string? Ro2GearFinalStrokeSec { get; set; }
        public string? Ro2GearFinalLoadSec { get; set; }
        public string? Ro2GearMainStroke { get; set; }
        public string? Ro2GearAbvalue { get; set; }
        public string? Ro2Gear2Date { get; set; }
        public string? Ro2Gear2Stroke { get; set; }
        public string? Ro2Gear2Load { get; set; }
        public string? Ro2Gear2FinalStroke { get; set; }
        public string? Ro2Gear2FinalLoad { get; set; }
        public string? Ro2Gear2StrokeSec { get; set; }
        public string? Ro2Gear2LoadSec { get; set; }
        public string? Ro2Gear2FinalStrokeSec { get; set; }
        public string? Ro2Gear2FinalLoadSec { get; set; }
        public string? Ro2Gear2MainStroke { get; set; }
        public string? Ro2Gear2Abvalue { get; set; }
        public string? Ro2DpntDate { get; set; }
        public string? Ro2DpntTorqueAxis1 { get; set; }
        public string? Ro2DpntAngleAxis1 { get; set; }
        public string? Ro2DpntJudgment { get; set; }
        public string? Ro2DpntSeating { get; set; }
        public string? Ro2DpntDrop { get; set; }
        public string? Ro2DpntSlack { get; set; }
        public string? Ro2DpnfMeasDate { get; set; }
        public string? Ro2DpnfFinalStroke { get; set; }
        public string? Ro2DpnfFinalLoad { get; set; }
        public string? Ro2DpnfMainStroke { get; set; }
        public string? Ro2Dfbrgdate { get; set; }
        public string? Ro2Dfbrgstroke { get; set; }
        public string? Ro2Dfbrgload { get; set; }
        public string? Ro2DfbrgfinalStroke { get; set; }
        public string? Ro2DfbrgfinalLoad { get; set; }
        public string? Ro2DfbrgstrokeSec { get; set; }
        public string? Ro2DfbrgloadSec { get; set; }
        public string? Ro2DfbrgfinalStrokeSec { get; set; }
        public string? Ro2DfbrgfinalLoadSec { get; set; }
        public string? Ro2DfbrgmainStroke { get; set; }
        public string? Ro2Df1date { get; set; }
        public string? Ro2Df1angleAxis1 { get; set; }
        public string? Ro2Df1codeAxis1 { get; set; }
        public string? Ro2Df1angleAxis2 { get; set; }
        public string? Ro2Df1codeAxis2 { get; set; }
        public string? Ro2Df1angleAxis3 { get; set; }
        public string? Ro2Df1codeAxis3 { get; set; }
        public string? Ro2Df1angleAxis4 { get; set; }
        public string? Ro2Df1codeAxis4 { get; set; }
        public string? Ro2Df1angleAxis5 { get; set; }
        public string? Ro2Df1codeAxis5 { get; set; }
        public string? Ro2Df1angleAxis6 { get; set; }
        public string? Ro2Df1codeAxis6 { get; set; }
        public string? Ro2Df1abvalue { get; set; }
        public string? Ro2Df2date { get; set; }
        public string? Ro2Df2angleAxis1 { get; set; }
        public string? Ro2Df2codeAxis1 { get; set; }
        public string? Ro2Df2angleAxis2 { get; set; }
        public string? Ro2Df2codeAxis2 { get; set; }
        public string? Ro2Df2angleAxis3 { get; set; }
        public string? Ro2Df2codeAxis3 { get; set; }
        public string? Ro2Df2angleAxis4 { get; set; }
        public string? Ro2Df2codeAxis4 { get; set; }
        public string? Ro2Df2angleAxis5 { get; set; }
        public string? Ro2Df2codeAxis5 { get; set; }
        public string? Ro2Df2angleAxis6 { get; set; }
        public string? Ro2Df2codeAxis6 { get; set; }
        public string? Ro2Df2abvalue { get; set; }
        public string? Ro2DfreverseDate { get; set; }
        public string? Ro2PokayokeDate36 { get; set; }
        public string? Ro2PokayokeDate37 { get; set; }
        public string? Ro2PokayokeDate38 { get; set; }
        public string? Ro2Mg1workTemp { get; set; }
        public string? Ro2Mg1fluxValue { get; set; }
        public string? Ro2Mg1dec { get; set; }
        public string? Ro2Mg2workTemp { get; set; }
        public string? Ro2Mg2fluxValue { get; set; }
        public string? Ro2Mg2dec { get; set; }
        public string? Ro2Asldate { get; set; }
        public string? Ro2Ictldate { get; set; }
        public string? Ro2Rcserial { get; set; }
        public string? Ro2AxisSerial { get; set; }
        public string? Ro2ProcDate { get; set; }
        public string? Ro2IsRcheat { get; set; }
        public string? Ro2HeatSt { get; set; }
        public string? Ro2HeatProcedure { get; set; }
        public string? Ro2RoomTemp { get; set; }
        public string? Ro2AxisTemp { get; set; }
        public string? Ro2CoreBefore { get; set; }
        public string? Ro2CoreAfter { get; set; }
        public string? Ro2Ihbefore { get; set; }
        public string? Ro2Ihafter { get; set; }
        public string? Ro2Cdtemp { get; set; }
        public string? Ro2HeatTime { get; set; }
        public string? Ro2HeatOutput { get; set; }
        public string? Ro2HeatEndTime { get; set; }
        public string? Ro2JudgmentCode { get; set; }
        public string? Ro2Apidate { get; set; }
        public string? Ro2Apistroke { get; set; }
        public string? Ro2Apiload { get; set; }
        public string? Ro2ApifinalStroke { get; set; }
        public string? Ro2ApimainStroke { get; set; }
        public string? Ro2ApicoreTemp { get; set; }
        public string? Ro2Apisttime { get; set; }
        public string? Ro2ApiinitTilt { get; set; }
        public string? Ro2Apipos { get; set; }
        public string? Ro2ApideviationLoad { get; set; }
        public string? Ro2Apicode { get; set; }
        public string? Ro2Apimachine { get; set; }
        public string? Ro2Ntdate { get; set; }
        public string? Ro2NttorqueAxis1 { get; set; }
        public string? Ro2NtangleAxis1 { get; set; }
        public string? Ro2Ntcode { get; set; }
        public string? Ro2Nthistory { get; set; }
        public string? Ro2Ntseating1 { get; set; }
        public string? Ro2Ntdrop1 { get; set; }
        public string? Ro2Ntslack1 { get; set; }
        public string? Ro2Rapdate { get; set; }
        public string? Ro2Rapbefore { get; set; }
        public string? Ro2Rapafter { get; set; }
        public string? Ro2Rapload { get; set; }
        public string? Ro2RapmainStroke { get; set; }
        public string? Ro2Rapcode { get; set; }
        public string? Ro2RapwashSensor { get; set; }
        public string? Ro2RapwashMain { get; set; }
        public string? Ro2RapwashPos { get; set; }
        public string? Ro2Rapstroke { get; set; }
        public string? Ro2RaploadSec { get; set; }
        public string? Ro2RapfinalStroke { get; set; }
        public string? Ro2Rapmain2Stroke { get; set; }
        public string? Ro2Rapcode2 { get; set; }
        public string? Ro2RtpstartDate { get; set; }
        public string? Ro2Rtpstroke { get; set; }
        public string? Ro2Rtpload { get; set; }
        public string? Ro2RtpfinalStroke { get; set; }
        public string? Ro2RtpmainStroke { get; set; }
        public string? Ro2Rtpcode { get; set; }
        public string? Ro2Rtphistory { get; set; }
        public string? Ro2Detection1 { get; set; }
        public string? Ro2Detection2 { get; set; }
    }
}
