using System;
using System.Collections.Generic;

namespace Traceability_System.Entity.Model
{
    public partial class VwGearTable
    {
        public string? GeDfringSerial { get; set; }
        public string? GePokayokeDate39 { get; set; }
        public string? GePokayokeDate40 { get; set; }
        public string? GeHsgBrgMeasDate { get; set; }
        public string? GeHsgBrgInflectPtStroke { get; set; }
        public string? GeHsgBrgInflectPtLoad { get; set; }
        public string? GeHsgBrgFinalStroke { get; set; }
        public string? GeHsgBrgFinalLoad { get; set; }
        public string? GeHsgBrgInflectPtStrokeSec { get; set; }
        public string? GeHsgBrgInflectPtLoadSec { get; set; }
        public string? GeHsgBrgFinalStrokeSec { get; set; }
        public string? GeHsgBrgFinalLoadSec { get; set; }
        public string? GeHsgBrgMaasterStroke { get; set; }
        public string? GePokayokeDate41 { get; set; }
        public string? GePokayokeDate42 { get; set; }
        public string? GePokayokeDate43 { get; set; }
        public string? GePokayokeDate44 { get; set; }
        public string? GeUpenderDate { get; set; }
        public string? GePokayokeDate45 { get; set; }
        public string? GeRejectTime { get; set; }
        public string? GePokayokeDate33 { get; set; }
        public string? GeDgameasDate { get; set; }
        public string? GeDgapos3Axis { get; set; }
        public string? GeDgaload3Axis { get; set; }
        public string? GeDgapos4Axis { get; set; }
        public string? GeDgaload4Axis { get; set; }
        public string? GePokayokeDate34 { get; set; }
        public string? GeDgmmeasDate { get; set; }
        public string? GeDgmdagjudge { get; set; }
        public string? GeDgmlhRh { get; set; }
        public string? GeDgmmaxTorque { get; set; }
        public string? GeDgmminTorque { get; set; }
        public string? GeDprmeasDate { get; set; }
        public string? GeDprfrs { get; set; }
        public string? GeDprfrl { get; set; }
        public string? GeContact { get; set; }
        public string? GePokayokeDate35 { get; set; }
        public string? GeGearMeasDate { get; set; }
        public string? GeGearStroke { get; set; }
        public string? GeGearLoad { get; set; }
        public string? GeGearFinalStroke { get; set; }
        public string? GeGearFinalLoad { get; set; }
        public string? GeGearStrokeSec { get; set; }
        public string? GeGearLoadSec { get; set; }
        public string? GeGearFinalStrokeSec { get; set; }
        public string? GeGearFinalLoadSec { get; set; }
        public string? GeGearMainStroke { get; set; }
        public string? GeGearAbvalue { get; set; }
        public string? GeGear2Date { get; set; }
        public string? GeGear2Stroke { get; set; }
        public string? GeGear2Load { get; set; }
        public string? GeGear2FinalStroke { get; set; }
        public string? GeGear2FinalLoad { get; set; }
        public string? GeGear2StrokeSec { get; set; }
        public string? GeGear2LoadSec { get; set; }
        public string? GeGear2FinalStrokeSec { get; set; }
        public string? GeGear2FinalLoadSec { get; set; }
        public string? GeGear2MainStroke { get; set; }
        public string? GeGear2Abvalue { get; set; }
        public string? GeDpntDate { get; set; }
        public string? GeDpntTorqueAxis1 { get; set; }
        public string? GeDpntAngleAxis1 { get; set; }
        public string? GeDpntJudgment { get; set; }
        public string? GeDpntSeating { get; set; }
        public string? GeDpntDrop { get; set; }
        public string? GeDpntSlack { get; set; }
        public string? GeDpnfMeasDate { get; set; }
        public string? GeDpnfFinalStroke { get; set; }
        public string? GeDpnfFinalLoad { get; set; }
        public string? GeDpnfMainStroke { get; set; }
        public string? GeDfbrgdate { get; set; }
        public string? GeDfbrgstroke { get; set; }
        public string? GeDfbrgload { get; set; }
        public string? GeDfbrgfinalStroke { get; set; }
        public string? GeDfbrgfinalLoad { get; set; }
        public string? GeDfbrgstrokeSec { get; set; }
        public string? GeDfbrgloadSec { get; set; }
        public string? GeDfbrgfinalStrokeSec { get; set; }
        public string? GeDfbrgfinalLoadSec { get; set; }
        public string? GeDfbrgmainStroke { get; set; }
        public string? GeDf1date { get; set; }
        public string? GeDf1angleAxis1 { get; set; }
        public string? GeDf1codeAxis1 { get; set; }
        public string? GeDf1angleAxis2 { get; set; }
        public string? GeDf1codeAxis2 { get; set; }
        public string? GeDf1angleAxis3 { get; set; }
        public string? GeDf1codeAxis3 { get; set; }
        public string? GeDf1angleAxis4 { get; set; }
        public string? GeDf1codeAxis4 { get; set; }
        public string? GeDf1angleAxis5 { get; set; }
        public string? GeDf1codeAxis5 { get; set; }
        public string? GeDf1angleAxis6 { get; set; }
        public string? GeDf1codeAxis6 { get; set; }
        public string? GeDf1abvalue { get; set; }
        public string? GeDf2date { get; set; }
        public string? GeDf2angleAxis1 { get; set; }
        public string? GeDf2codeAxis1 { get; set; }
        public string? GeDf2angleAxis2 { get; set; }
        public string? GeDf2codeAxis2 { get; set; }
        public string? GeDf2angleAxis3 { get; set; }
        public string? GeDf2codeAxis3 { get; set; }
        public string? GeDf2angleAxis4 { get; set; }
        public string? GeDf2codeAxis4 { get; set; }
        public string? GeDf2angleAxis5 { get; set; }
        public string? GeDf2codeAxis5 { get; set; }
        public string? GeDf2angleAxis6 { get; set; }
        public string? GeDf2codeAxis6 { get; set; }
        public string? GeDf2abvalue { get; set; }
        public string? GeDfreverseDate { get; set; }
        public string? GePinposition { get; set; }
        public string? GePokayokeDate36 { get; set; }
        public string? GePokayokeDate37 { get; set; }
        public string? GePokayokeDate38 { get; set; }
        public string? GeMg1workTemp { get; set; }
        public string? GeMg1fluxValue { get; set; }
        public string? GeMg1dec { get; set; }
        public string? GeMg2workTemp { get; set; }
        public string? GeMg2fluxValue { get; set; }
        public string? GeMg2dec { get; set; }
        public string? GeAsldate { get; set; }
        public string? GeIctldate { get; set; }
        public string? GeRcserial { get; set; }
        public string? GeAxisSerial { get; set; }
        public string? GeProcDate { get; set; }
        public string? GeIsRcheat { get; set; }
        public string? GeHeatSt { get; set; }
        public string? GeHeatProcedure { get; set; }
        public string? GeRoomTemp { get; set; }
        public string? GeAxisTemp { get; set; }
        public string? GeCoreBefore { get; set; }
        public string? GeCoreAfter { get; set; }
        public string? GeIhbefore { get; set; }
        public string? GeIhafter { get; set; }
        public string? GeCdtemp { get; set; }
        public string? GeHeatTime { get; set; }
        public string? GeHeatOutput { get; set; }
        public string? GeHeatEndTime { get; set; }
        public string? GeJudgmentCode { get; set; }
        public string? GeApidate { get; set; }
        public string? GeApistroke { get; set; }
        public string? GeApiload { get; set; }
        public string? GeApifinalStroke { get; set; }
        public string? GeApimainStroke { get; set; }
        public string? GeApicoreTemp { get; set; }
        public string? GeApisttime { get; set; }
        public string? GeApiinitTilt { get; set; }
        public string? GeApipos { get; set; }
        public string? GeApideviationLoad { get; set; }
        public string? GeApicode { get; set; }
        public string? GeApimachine { get; set; }
        public string? GeNtdate { get; set; }
        public string? GeNttorqueAxis1 { get; set; }
        public string? GeNtangleAxis1 { get; set; }
        public string? GeNtcode { get; set; }
        public string? GeNthistory { get; set; }
        public string? GeNtseating1 { get; set; }
        public string? GeNtdrop1 { get; set; }
        public string? GeNtslack1 { get; set; }
        public string? GeRapdate { get; set; }
        public string? GeRapbefore { get; set; }
        public string? GeRapafter { get; set; }
        public string? GeRapload { get; set; }
        public string? GeRapmainStroke { get; set; }
        public string? GeRapcode { get; set; }
        public string? GeRapwashSensor { get; set; }
        public string? GeRapwashMain { get; set; }
        public string? GeRapwashPos { get; set; }
        public string? GeRapstroke { get; set; }
        public string? GeRaploadSec { get; set; }
        public string? GeRapfinalStroke { get; set; }
        public string? GeRapmain2Stroke { get; set; }
        public string? GeRapcode2 { get; set; }
        public string? GeRtpstartDate { get; set; }
        public string? GeRtpstroke { get; set; }
        public string? GeRtpload { get; set; }
        public string? GeRtpfinalStroke { get; set; }
        public string? GeRtpmainStroke { get; set; }
        public string? GeRtpcode { get; set; }
        public string? GeRtphistory { get; set; }
    }
}
