using System;
using System.Collections.Generic;

namespace Traceability_System.Entity.Models
{
    public partial class MotorTable
    {
        public int Id { get; set; }
        public string? InterNo { get; set; }
        public string? CaseDec { get; set; }
        public string? RrCoverDec { get; set; }
        public string? ParkingDec { get; set; }
        public string? GearDec { get; set; }
        public string? DefLingDec { get; set; }
        public string? HsgDec { get; set; }
        public string? Mg1statorDec { get; set; }
        public string? Mg2statorDec { get; set; }
        public string? Mg1rotorDec { get; set; }
        public string? Mg2rotorDec { get; set; }
        public string? LineDec { get; set; }
        public string? Dfcase { get; set; }
        public string? OilPump { get; set; }
        public string? CaseSerial { get; set; }
        public string? HsgSerial { get; set; }
        public string? Mg1sserial { get; set; }
        public string? Mg2sserial { get; set; }
        public string? Mg1rserial { get; set; }
        public string? Mg2rserial { get; set; }
        public string? CoDriveSerial { get; set; }
        public string? MoDriveSerial { get; set; }
        public string? DrivenSerial { get; set; }
        public string? DorpinSerial { get; set; }
        public string? DfringSerial { get; set; }
        public string? DfcaseSerial { get; set; }
        public string? RrcoverSerial { get; set; }
        public string? ShipmentSerial { get; set; }
        public string? RropSerial { get; set; }
        public string? RotorShaftTrans { get; set; }
        public string? RotorCoreTrans { get; set; }
        public string? RotorHeating { get; set; }
        public string? RotorShaftPress { get; set; }
        public string? RotorNutTight { get; set; }
        public string? RotorForeignSuction { get; set; }
        public string? RotorNutCrimpMg1press { get; set; }
        public string? RotorResolverPress { get; set; }
        public string? RotorReject { get; set; }
        public string? RotorMagnetization { get; set; }
        public string? RotorExtractionInsp { get; set; }
        public string? RotorShippingInsp { get; set; }
        public string? RotorTamg2shaftTrans { get; set; }
        public string? RotorTamg2coreTrans { get; set; }
        public string? RotorTamg2heating { get; set; }
        public string? RotorTamg2shaftPress { get; set; }
        public string? RotorTamg2nutTight { get; set; }
        public string? RotorTamg2foreignSuction { get; set; }
        public string? RotorTamg2nutCrimpMg1press { get; set; }
        public string? RotorTamg2resolverPress { get; set; }
        public string? RotorTamg2reject { get; set; }
        public string? RotorTamg2magnetization { get; set; }
        public string? RotorTamg2extractionInsp { get; set; }
        public string? RotorTamg2shippingInsp { get; set; }
        public string? MotorMtrCode { get; set; }
        public string? MotorSngen { get; set; }
        public string? MotorHsgSrfBrgAm { get; set; }
        public string? MotorHsgSrfKnockPam { get; set; }
        public string? MotorCoolPipeMw { get; set; }
        public string? MotorTermBoardMw { get; set; }
        public string? MotorRrCoverSrfOutBrgAm { get; set; }
        public string? MotorRrCoverSrfKnockPam { get; set; }
        public string? MotorMg1statorInsAm { get; set; }
        public string? MotorMg2statorInsAm { get; set; }
        public string? MotorHarnEscMw { get; set; }
        public string? MotorMg12statorTightAm { get; set; }
        public string? MotorThermMw { get; set; }
        public string? MotorCoolPipeMw2 { get; set; }
        public string? MotorMg12rotorAssem { get; set; }
        public string? MotorFipgapp { get; set; }
        public string? MotorRrCoverAssem { get; set; }
        public string? MotorRrCoverTight1 { get; set; }
        public string? MotorRrCoverTight2 { get; set; }
        public string? MotorInvMw { get; set; }
        public string? MotorMw1 { get; set; }
        public string? MotorMw2 { get; set; }
        public string? MotorPrevStn { get; set; }
        public string? MotorMwco0 { get; set; }
        public string? MotorMwco1 { get; set; }
        public string? MotorMwco2 { get; set; }
        public string? MotorMwco3 { get; set; }
        public string? MotorReject { get; set; }
        public string? CoverSubIdsetSpare { get; set; }
        public string? CoverSubRrCovSetDmread { get; set; }
        public string? CoverSubRrCovBrgPressEquip { get; set; }
        public string? CoverSubMw1 { get; set; }
        public string? CoverSubMw2 { get; set; }
        public string? CoverSubMw3 { get; set; }
        public string? CoverSubMw4 { get; set; }
        public string? CoverSubRrRevEquip { get; set; }
        public string? CoverSubWaterConnTighten { get; set; }
        public string? CoverSubReject { get; set; }
        public string? DefDfcaseRead { get; set; }
        public string? DefDfpinionShaftEquip { get; set; }
        public string? DefDiffOperMeasureEquip { get; set; }
        public string? DefTweezersMw { get; set; }
        public string? DefDiffPinionPress { get; set; }
        public string? Dmread { get; set; }
        public string? GearPressIn1 { get; set; }
        public string? GearPressIn2 { get; set; }
        public string? Slnffastening { get; set; }
        public string? Slnfriveting { get; set; }
        public string? DiffBrgPressIn { get; set; }
        public string? DiffBoltTight1 { get; set; }
        public string? DiffBoltTight2 { get; set; }
        public string? RevRivetConfirm { get; set; }
        public string? DamperImage { get; set; }
        public string? Reject { get; set; }
        public string? Idwrite { get; set; }
        public string? HsgSubShimSel { get; set; }
        public string? HsgBrgPressIn1 { get; set; }
        public string? HsgBrgPressIn2 { get; set; }
        public string? GearAssembly1 { get; set; }
        public string? OilPumpAssembly { get; set; }
        public string? SubShimSel { get; set; }
        public string? ShimSet { get; set; }
        public string? LubPipeAssem { get; set; }
        public string? CaseFipgapp { get; set; }
        public string? AssemJoining1 { get; set; }
        public string? AssemTight1 { get; set; }
        public string? AssemTight2 { get; set; }
        public string? DrainPlugTight { get; set; }
        public string? DiffOilsealPress1 { get; set; }
        public string? DiffOilsealPress2 { get; set; }
        public string? FillerTight { get; set; }
        public string? AssyUpright { get; set; }
        public string? Idexchange { get; set; }
        public string? OilCoolerAssem { get; set; }
        public string? MandrelAttach { get; set; }
        public string? Preprocessing { get; set; }
        public string? AssyLeakTest { get; set; }
        public string? Insulation { get; set; }
        public string? OilInjection { get; set; }
        public string? AssyNoiseTest { get; set; }
        public string? Mw1 { get; set; }
        public string? Mw2 { get; set; }
        public string? Mw3 { get; set; }
        public string? SerialStamping { get; set; }
        public string? ShippingPrep1 { get; set; }
        public string? ShippingPrep2 { get; set; }
        public string? VisualInsp { get; set; }
        public string? Fipgreject { get; set; }
        public string? LabelPrinting { get; set; }
        public string? Reshuffle { get; set; }
        public string? PokayokeDate1 { get; set; }
        public string? PokayokeDate2 { get; set; }
        public string? HsgBrgDate { get; set; }
        public string? HsgBrgStroke { get; set; }
        public string? HsgBrgLoad { get; set; }
        public string? HsgBrgFinalStroke { get; set; }
        public string? HsgBrgFinalLoad { get; set; }
        public string? HsgBrgStrokeSec { get; set; }
        public string? HsgBrgLoadSec { get; set; }
        public string? HsgBrgFinalStrokeSec { get; set; }
        public string? HsgBrgFinalLoadSec { get; set; }
        public string? HsgBrgMainStroke { get; set; }
        public string? HsgBrgAbvalue { get; set; }
        public string? HsgKnockDate { get; set; }
        public string? HsgKnockStroke { get; set; }
        public string? HsgKnockLoad { get; set; }
        public string? HsgKnockFinalStroke { get; set; }
        public string? HsgKnockFinalLoad { get; set; }
        public string? HsgKnockStrokeSec { get; set; }
        public string? HsgKnockLoadSec { get; set; }
        public string? HsgKnockFinalStrokeSec { get; set; }
        public string? HsgKnockFinalLoadSec { get; set; }
        public string? HsgKnockMainStroke { get; set; }
        public string? HsgKnockAbvalue { get; set; }
        public string? PokayokeDate3 { get; set; }
        public string? PokayokeDate4 { get; set; }
        public string? RrbrgDate { get; set; }
        public string? RrbrgStroke { get; set; }
        public string? RrbrgLoad { get; set; }
        public string? RrbrgFinalStroke { get; set; }
        public string? RrbrgFinalLoad { get; set; }
        public string? RrbrgStrokeSec { get; set; }
        public string? RrbrgLoadSec { get; set; }
        public string? RrbrgFinalStrokeSec { get; set; }
        public string? RrbrgFinalLoadSec { get; set; }
        public string? RrbrgMainStroke { get; set; }
        public string? RrbrgAbvalue { get; set; }
        public string? RrknockDate { get; set; }
        public string? RrknockStroke { get; set; }
        public string? RrknockLoad { get; set; }
        public string? RrknockFinalStroke { get; set; }
        public string? RrknockFinalLoad { get; set; }
        public string? RrknockStrokeSec { get; set; }
        public string? RrknockLoadSec { get; set; }
        public string? RrknockFinalStrokeSec { get; set; }
        public string? RrknockFinalLoadSec { get; set; }
        public string? RrknockMainStroke { get; set; }
        public string? RrknockAbvalue { get; set; }
        public string? Mg1date { get; set; }
        public string? Mg1torqAngleAxis1 { get; set; }
        public string? Mg1codeAxis1 { get; set; }
        public string? Mg1torqAngleAxis2 { get; set; }
        public string? Mg1codeAxis2 { get; set; }
        public string? Mg1torqAngleAxis3 { get; set; }
        public string? Mg1codeAxis3 { get; set; }
        public string? Mg2date { get; set; }
        public string? Mg2torqAngleAxis1 { get; set; }
        public string? Mg2codeAxis1 { get; set; }
        public string? Mg2torqAngleAxis2 { get; set; }
        public string? Mg2codeAxis2 { get; set; }
        public string? Mg2torqAngleAxis3 { get; set; }
        public string? Mg2codeAxis3 { get; set; }
        public string? PokayokeDate5 { get; set; }
        public string? StatorDate { get; set; }
        public string? TorqAngleAxis1 { get; set; }
        public string? CodeAxis1 { get; set; }
        public string? TorqAngleAxis2 { get; set; }
        public string? CodeAxis2 { get; set; }
        public string? TorqAngleAxis3 { get; set; }
        public string? CodeAxis3 { get; set; }
        public string? AngleAxis1Sec { get; set; }
        public string? AxisCode1Sec { get; set; }
        public string? AngleAxis2Sec { get; set; }
        public string? AxisCode2Sec { get; set; }
        public string? AngleAxis3Sec { get; set; }
        public string? AxisCode3Sec { get; set; }
        public string? Mg1stator1 { get; set; }
        public string? Mg1stator2 { get; set; }
        public string? Mg1stator3 { get; set; }
        public string? Mg2stator1 { get; set; }
        public string? Mg2stator2 { get; set; }
        public string? Mg2stator3 { get; set; }
        public string? PokayokeDate6 { get; set; }
        public string? PokayokeDate7 { get; set; }
        public string? MeasDate { get; set; }
        public string? Mg1workTemp { get; set; }
        public string? Mg1fluxValue { get; set; }
        public string? Mg1dec { get; set; }
        public string? Mg2workTemp { get; set; }
        public string? Mg2fluxValue { get; set; }
        public string? Mg2dec { get; set; }
        public string? RrFigpdate { get; set; }
        public string? ImgResult { get; set; }
        public string? RrcoverDate { get; set; }
        public string? TotalDate1 { get; set; }
        public string? Total1AngleAxis1 { get; set; }
        public string? Total1Axis1Code { get; set; }
        public string? Total1AngleAxis2 { get; set; }
        public string? Total1Axis2Code { get; set; }
        public string? Total1AngleAxis3 { get; set; }
        public string? Total1Axis3Code { get; set; }
        public string? Total1AngleAxis4 { get; set; }
        public string? Total1Axis4Code { get; set; }
        public string? Total1AngleAxis5 { get; set; }
        public string? Total1Axis5Code { get; set; }
        public string? Total1AngleAxis6 { get; set; }
        public string? Total1Axis6Code { get; set; }
        public string? Total1AngleAxis7 { get; set; }
        public string? Total1Axis7Code { get; set; }
        public string? Total1AngleAxis8 { get; set; }
        public string? Total1Axis8Code { get; set; }
        public string? Total1AngleAxis9 { get; set; }
        public string? Total1Axis9Code { get; set; }
        public string? Total1AngleAxis10 { get; set; }
        public string? Total1Axis10Code { get; set; }
        public string? Total1AngleAxis11 { get; set; }
        public string? Total1Axis11Code { get; set; }
        public string? Total1Abvalue { get; set; }
        public string? Total2Date { get; set; }
        public string? Angle1Axis { get; set; }
        public string? Axis1Code { get; set; }
        public string? Angle2Axis { get; set; }
        public string? Axis2Code { get; set; }
        public string? Angle3Axis { get; set; }
        public string? Axis3Code { get; set; }
        public string? Angle4Axis { get; set; }
        public string? Axis4Code { get; set; }
        public string? Angle5Axis { get; set; }
        public string? Axis5Code { get; set; }
        public string? Angle6Axis { get; set; }
        public string? Axis6Code { get; set; }
        public string? Angle7Axis { get; set; }
        public string? Axis7Code { get; set; }
        public string? Angle8Axis { get; set; }
        public string? Axis8Code { get; set; }
        public string? Angle9Axis { get; set; }
        public string? Axis9Code { get; set; }
        public string? Angle10Axis { get; set; }
        public string? Axis10Code { get; set; }
        public string? Ab { get; set; }
        public string? ReDate { get; set; }
        public string? PokayokeDateBas { get; set; }
        public string? PokayokeDate8 { get; set; }
        public string? PokayokeDate9 { get; set; }
        public string? PokayokeDate10 { get; set; }
        public string? PokayokeDate11 { get; set; }
        public string? PokayokeDate12 { get; set; }
        public string? PokayokeDate13 { get; set; }
        public string? PokayokeDate14 { get; set; }
        public DateTime? CollectionDate { get; set; }
        public int? Number { get; set; }
    }
}
