using System;
using System.Collections.Generic;

namespace Traceability_System.Entity.Models
{
    public partial class Tatable
    {
        public int Id { get; set; }
        public string? InterNo { get; set; }
        public string? CaseDec { get; set; }
        public string? RrCoverDec { get; set; }
        public string? ParkingDec { get; set; }
        public string? GearDec { get; set; }
        public string? DefLingDec { get; set; }
        public string? HsgDec { get; set; }
        public string? Mg1statorDec { get; set; }
        public string? Mg2statorDec { get; set; }
        public string? Mg1rotorDec { get; set; }
        public string? Mg2rotorDec { get; set; }
        public string? LineDec { get; set; }
        public string? Dfcase { get; set; }
        public string? OilPump { get; set; }
        public string? CaseSerial { get; set; }
        public string? HsgSerial { get; set; }
        public string? Mg1sserial { get; set; }
        public string? Mg2sserial { get; set; }
        public string? Mg1rserial { get; set; }
        public string? Mg2rserial { get; set; }
        public string? CoDriveSerial { get; set; }
        public string? MoDriveSerial { get; set; }
        public string? DrivenSerial { get; set; }
        public string? DorpinSerial { get; set; }
        public string? DfringSerial { get; set; }
        public string? DfcaseSerial { get; set; }
        public string? RrcoverSerial { get; set; }
        public string? ShipmentSerial { get; set; }
        public string? RropSerial { get; set; }
        public string? RotorShaftTrans { get; set; }
        public string? RotorCoreTrans { get; set; }
        public string? RotorHeating { get; set; }
        public string? RotorShaftPress { get; set; }
        public string? RotorNutTight { get; set; }
        public string? RotorForeignSuction { get; set; }
        public string? RotorNutCrimpMg1press { get; set; }
        public string? RotorResolverPress { get; set; }
        public string? RotorReject { get; set; }
        public string? RotorMagnetization { get; set; }
        public string? RotorExtractionInsp { get; set; }
        public string? RotorShippingInsp { get; set; }
        public string? RotorTamg2shaftTrans { get; set; }
        public string? RotorTamg2coreTrans { get; set; }
        public string? RotorTamg2heating { get; set; }
        public string? RotorTamg2shaftPress { get; set; }
        public string? RotorTamg2nutTight { get; set; }
        public string? RotorTamg2foreignSuction { get; set; }
        public string? RotorTamg2nutCrimpMg1press { get; set; }
        public string? RotorTamg2resolverPress { get; set; }
        public string? RotorTamg2reject { get; set; }
        public string? RotorTamg2magnetization { get; set; }
        public string? RotorTamg2extractionInsp { get; set; }
        public string? RotorTamg2shippingInsp { get; set; }
        public string? MotorMtrCode { get; set; }
        public string? MotorSngen { get; set; }
        public string? MotorHsgSrfBrgAm { get; set; }
        public string? MotorHsgSrfKnockPam { get; set; }
        public string? MotorCoolPipeMw { get; set; }
        public string? MotorTermBoardMw { get; set; }
        public string? MotorRrCoverSrfOutBrgAm { get; set; }
        public string? MotorRrCoverSrfKnockPam { get; set; }
        public string? MotorMg1statorInsAm { get; set; }
        public string? MotorMg2statorInsAm { get; set; }
        public string? MotorHarnEscMw { get; set; }
        public string? MotorMg12statorTightAm { get; set; }
        public string? MotorThermMw { get; set; }
        public string? MotorCoolPipeMw2 { get; set; }
        public string? MotorMg12rotorAssem { get; set; }
        public string? MotorFipgapp { get; set; }
        public string? MotorRrCoverAssem { get; set; }
        public string? MotorRrCoverTight1 { get; set; }
        public string? MotorRrCoverTight2 { get; set; }
        public string? MotorInvMw { get; set; }
        public string? MotorMw1 { get; set; }
        public string? MotorMw2 { get; set; }
        public string? MotorPrevStn { get; set; }
        public string? MotorMwco0 { get; set; }
        public string? MotorMwco1 { get; set; }
        public string? MotorMwco2 { get; set; }
        public string? MotorMwco3 { get; set; }
        public string? MotorReject { get; set; }
        public string? CoverSubIdsetSpare { get; set; }
        public string? CoverSubRrCovSetDmread { get; set; }
        public string? CoverSubRrCovBrgPressEquip { get; set; }
        public string? CoverSubMw1 { get; set; }
        public string? CoverSubMw2 { get; set; }
        public string? CoverSubMw3 { get; set; }
        public string? CoverSubMw4 { get; set; }
        public string? CoverSubRrRevEquip { get; set; }
        public string? CoverSubWaterConnTighten { get; set; }
        public string? CoverSubReject { get; set; }
        public string? DefDfcaseRead { get; set; }
        public string? DefDfpinionShaftEquip { get; set; }
        public string? DefDiffOperMeasureEquip { get; set; }
        public string? DefTweezersMw { get; set; }
        public string? DefDiffPinionPress { get; set; }
        public string? Dmread { get; set; }
        public string? GearPressIn1 { get; set; }
        public string? GearPressIn2 { get; set; }
        public string? Slnffastening { get; set; }
        public string? Slnfriveting { get; set; }
        public string? DiffBrgPressIn { get; set; }
        public string? DiffBoltTight1 { get; set; }
        public string? DiffBoltTight2 { get; set; }
        public string? RevRivetConfirm { get; set; }
        public string? DamperImage { get; set; }
        public string? Reject { get; set; }
        public string? Idwrite { get; set; }
        public string? HsgSubShimSel { get; set; }
        public string? HsgBrgPressIn1 { get; set; }
        public string? HsgBrgPressIn2 { get; set; }
        public string? GearAssembly1 { get; set; }
        public string? OilPumpAssembly { get; set; }
        public string? SubShimSel { get; set; }
        public string? ShimSet { get; set; }
        public string? LubPipeAssem { get; set; }
        public string? CaseFipgapp { get; set; }
        public string? AssemJoining1 { get; set; }
        public string? AssemTight1 { get; set; }
        public string? AssemTight2 { get; set; }
        public string? DrainPlugTight { get; set; }
        public string? DiffOilsealPress1 { get; set; }
        public string? DiffOilsealPress2 { get; set; }
        public string? FillerTight { get; set; }
        public string? AssyUpright { get; set; }
        public string? Idexchange { get; set; }
        public string? OilCoolerAssem { get; set; }
        public string? MandrelAttach { get; set; }
        public string? Preprocessing { get; set; }
        public string? AssyLeakTest { get; set; }
        public string? Insulation { get; set; }
        public string? OilInjection { get; set; }
        public string? AssyNoiseTest { get; set; }
        public string? Mw1 { get; set; }
        public string? Mw2 { get; set; }
        public string? Mw3 { get; set; }
        public string? SerialStamping { get; set; }
        public string? ShippingPrep1 { get; set; }
        public string? ShippingPrep2 { get; set; }
        public string? VisualInsp { get; set; }
        public string? Fipgreject { get; set; }
        public string? LabelPrinting { get; set; }
        public string? Reshuffle { get; set; }
        public string? PokayokeDate15 { get; set; }
        public string? PokayokeDate16 { get; set; }
        public string? TagMeasDate { get; set; }
        public string? PokayokeDate18 { get; set; }
        public string? PokayokeDate19 { get; set; }
        public string? ShimMeasDate { get; set; }
        public string? ShimHsgt7 { get; set; }
        public string? ShimHsgt5 { get; set; }
        public string? ShimHsgt3 { get; set; }
        public string? ShimHsgt1 { get; set; }
        public string? ShimShellt8 { get; set; }
        public string? ShimShellt6 { get; set; }
        public string? ShimCaset4 { get; set; }
        public string? ShimCaset2 { get; set; }
        public string? ShimSlider { get; set; }
        public string? ShimGrade { get; set; }
        public string? ShimGradeCo { get; set; }
        public string? ShimGradeIn { get; set; }
        public string? ShimValueDiff { get; set; }
        public string? ShimValuePin { get; set; }
        public string? ShimValueCo { get; set; }
        public string? ShimValueIn { get; set; }
        public string? ShimGear { get; set; }
        public string? Shimt1t2 { get; set; }
        public string? Shimt3t4 { get; set; }
        public string? Shimt5t6 { get; set; }
        public string? Shimt7t8 { get; set; }
        public string? Shimt1Main { get; set; }
        public string? Shimt3Main { get; set; }
        public string? Shimt5Main { get; set; }
        public string? Shimt7Main { get; set; }
        public string? Shimt2Main { get; set; }
        public string? Shimt4Main { get; set; }
        public string? Shimt6Main { get; set; }
        public string? Shimt8Main { get; set; }
        public string? Hsg1MeasDate { get; set; }
        public string? Hsg1Stroke { get; set; }
        public string? Hsg1PtLoad { get; set; }
        public string? Hsg1FinalStroke { get; set; }
        public string? Hsg1FinalLoad { get; set; }
        public string? Hsg1StrokeSec { get; set; }
        public string? Hsg1PtLoadSec { get; set; }
        public string? Hsg1FinalStrokeSec { get; set; }
        public string? Hsg1FinalLoadSec { get; set; }
        public string? Hsg1MainStroke { get; set; }
        public string? Hsg1Abvalue { get; set; }
        public string? Hsg2Date { get; set; }
        public string? Hsg2Stroke { get; set; }
        public string? Hsg2PtLoad { get; set; }
        public string? Hsg2FinalStroke { get; set; }
        public string? Hsg2FinalLoad { get; set; }
        public string? Hsg2StrokeSec { get; set; }
        public string? Hsg2PtLoadSec { get; set; }
        public string? Hsg2FinalStrokeSec { get; set; }
        public string? Hsg2FinalLoadSec { get; set; }
        public string? Hsg2MainStroke { get; set; }
        public string? Hsg2Abvalue { get; set; }
        public string? PokayokeDate20 { get; set; }
        public string? HsgFigpDate { get; set; }
        public string? HsgFigpportrait { get; set; }
        public string? HsgFitDate { get; set; }
        public string? Hsg1Date { get; set; }
        public string? Hsg1AngleAxis1 { get; set; }
        public string? Hsg1CodeAxis1 { get; set; }
        public string? Hsg1AngleAxis2 { get; set; }
        public string? Hsg1CodeAxis2 { get; set; }
        public string? Hsg1AngleAxis3 { get; set; }
        public string? Hsg1CodeAxis3 { get; set; }
        public string? Hsg1AngleAxis4 { get; set; }
        public string? Hsg1CodeAxis4 { get; set; }
        public string? Hsg1AngleAxis5 { get; set; }
        public string? Hsg1CodeAxis5 { get; set; }
        public string? Hsg1AngleAxis6 { get; set; }
        public string? Hsg1CodeAxis6 { get; set; }
        public string? Hsg1AngleAxis7 { get; set; }
        public string? Hsg1CodeAxis7 { get; set; }
        public string? Hsg1AngleAxis8 { get; set; }
        public string? Hsg1CodeAxis8 { get; set; }
        public string? Hsg1AngleAxis9 { get; set; }
        public string? Hsg1CodeAxis9 { get; set; }
        public string? Hsg1AngleAxis10 { get; set; }
        public string? Hsg1CodeAxis10 { get; set; }
        public string? Hsg1AngleAxis11 { get; set; }
        public string? Hsg1CodeAxis11 { get; set; }
        public string? Hsg1Ab { get; set; }
        public string? Hsg2MaesDate { get; set; }
        public string? Hsg2AngleAxis1 { get; set; }
        public string? Hsg2CodeAxis1 { get; set; }
        public string? Hsg2AngleAxis2 { get; set; }
        public string? Hsg2CodeAxis2 { get; set; }
        public string? Hsg2AngleAxis3 { get; set; }
        public string? Hsg2CodeAxis3 { get; set; }
        public string? Hsg2AngleAxis4 { get; set; }
        public string? Hsg2CodeAxis4 { get; set; }
        public string? Hsg2AngleAxis5 { get; set; }
        public string? Hsg2CodeAxis5 { get; set; }
        public string? Hsg2AngleAxis6 { get; set; }
        public string? Hsg2CodeAxis6 { get; set; }
        public string? Hsg2AngleAxis7 { get; set; }
        public string? Hsg2CodeAxis7 { get; set; }
        public string? Hsg2AngleAxis8 { get; set; }
        public string? Hsg2CodeAxis8 { get; set; }
        public string? Hsg2AngleAxis9 { get; set; }
        public string? Hsg2CodeAxis9 { get; set; }
        public string? Hsg2AngleAxis10 { get; set; }
        public string? Hsg2CodeAxis10 { get; set; }
        public string? Hsg2AngleAxis11 { get; set; }
        public string? Hsg2CodeAxis11 { get; set; }
        public string? Hsg2Ab { get; set; }
        public string? PokayokeDate27 { get; set; }
        public string? Os1date { get; set; }
        public string? Os1lhstroke { get; set; }
        public string? Os1lhload { get; set; }
        public string? Os1lhfinalStroke { get; set; }
        public string? Os1lhfinalLoad { get; set; }
        public string? Os1rhstroke { get; set; }
        public string? Os1rhload { get; set; }
        public string? Os1rhfinalStroke { get; set; }
        public string? Os1rhfinalLoad { get; set; }
        public string? Os1mainStroke { get; set; }
        public string? Os1abvalue { get; set; }
        public string? Os2date { get; set; }
        public string? Os2stroke { get; set; }
        public string? Os2ptLoad { get; set; }
        public string? Os2finalStroke { get; set; }
        public string? Os2finalLoad { get; set; }
        public string? Os2mainStroke { get; set; }
        public string? Os2abvalue { get; set; }
        public string? PokayokeDate21 { get; set; }
        public string? AssyDate { get; set; }
        public string? PokayokeDate22 { get; set; }
        public string? PokayokeDate23 { get; set; }
        public string? PokayokeDate24 { get; set; }
        public string? PokayokeDate25 { get; set; }
        public string? LeakDate { get; set; }
        public string? LeakGear { get; set; }
        public string? LeakCorrect { get; set; }
        public string? LeakTempDec { get; set; }
        public string? LeakMain { get; set; }
        public string? LeakFrontOil { get; set; }
        public string? LeakEtaf { get; set; }
        public string? LeakLastOil { get; set; }
        public string? LeakTemp { get; set; }
        public string? LeakHumidity { get; set; }
        public string? LeakOilTempDec { get; set; }
        public string? LeakMg1mohm { get; set; }
        public string? LeakMg1dec { get; set; }
        public string? LeakMg2mohm { get; set; }
        public string? LeakMg2dec { get; set; }
        public string? LeakMg1dielectric { get; set; }
        public string? LeakMg1dielectricDec { get; set; }
        public string? LeakMg2dielectric { get; set; }
        public string? LeakMg2dielectricDec { get; set; }
        public string? LeakThermistor { get; set; }
        public string? LeakThermistorDec { get; set; }
        public string? LeakResolver { get; set; }
        public string? LeakResolverDec { get; set; }
        public string? LeakOilTempMohmDec { get; set; }
        public string? LeakMg1uv { get; set; }
        public string? LeakMg1uvdec { get; set; }
        public string? LeakMg1uw { get; set; }
        public string? LeakMg1uwdec { get; set; }
        public string? LeakMg1wu { get; set; }
        public string? LeakMg1wudec { get; set; }
        public string? LeakMg2uv { get; set; }
        public string? LeakMg2uvdec { get; set; }
        public string? LeakMg2uw { get; set; }
        public string? LeakMg2uwdec { get; set; }
        public string? LeakMg2wu { get; set; }
        public string? LeakMg2wudec { get; set; }
        public string? LeakThermistorMg1 { get; set; }
        public string? LeakThermistorMg1dec { get; set; }
        public string? LeakThermistorMg2 { get; set; }
        public string? LeakThermistorMg2dec { get; set; }
        public string? LeakOilLine { get; set; }
        public string? LeakOilLineDec { get; set; }
        public string? LeakMg1rotateDec { get; set; }
        public string? LeakMg2rotateDec { get; set; }
        public string? LeakMg1wmg2v { get; set; }
        public string? LeakOil { get; set; }
        public string? LeakMg196 { get; set; }
        public string? LeakMg196dec { get; set; }
        public string? LeakMg11410 { get; set; }
        public string? LeakMg11410dec { get; set; }
        public string? LeakMg1135 { get; set; }
        public string? LeakMg1135dec { get; set; }
        public string? LeakMg281 { get; set; }
        public string? LeakMg281dec { get; set; }
        public string? LeakMg2117 { get; set; }
        public string? LeakMg2117dec { get; set; }
        public string? LeakMg232 { get; set; }
        public string? LeakMg232dec { get; set; }
        public string? LeakCol { get; set; }
        public string? IssDate { get; set; }
        public string? IssP { get; set; }
        public string? IssnotP { get; set; }
        public string? IssFunction { get; set; }
        public string? IssMg1uv { get; set; }
        public string? IssMg1uvdec { get; set; }
        public string? IssMg1vw { get; set; }
        public string? IssMg1vwdec { get; set; }
        public string? IssMg2uv { get; set; }
        public string? IssMg2uvdec { get; set; }
        public string? IssMg2vw { get; set; }
        public string? IssMg2vwdec { get; set; }
        public string? IssMg1value { get; set; }
        public string? IssMg1valueDec { get; set; }
        public string? IssMg2value { get; set; }
        public string? IssMg2valueDec { get; set; }
        public string? IssMg1disUv { get; set; }
        public string? IssMg1disUvdec { get; set; }
        public string? IssMg1disVw { get; set; }
        public string? IssMg1disVwdec { get; set; }
        public string? IssMg2disUv { get; set; }
        public string? IssMg2disUvdec { get; set; }
        public string? IssMg2disVw { get; set; }
        public string? IssMg2disVwdec { get; set; }
        public string? IssMg2gear { get; set; }
        public string? IssMg2gearDec { get; set; }
        public string? IssRevup { get; set; }
        public string? IssSlowup { get; set; }
        public string? IssRevCounter { get; set; }
        public string? IssRevLast { get; set; }
        public string? IssSlowCounter { get; set; }
        public string? IssSlowLast { get; set; }
        public string? IssRevAvg { get; set; }
        public string? IssRevAvgDec { get; set; }
        public string? IssSlowAvg { get; set; }
        public string? IssSlowAvgDec { get; set; }
        public string? IssOilTemp { get; set; }
        public string? IssRev1Noise { get; set; }
        public string? IssRev1Rate { get; set; }
        public string? IssRev1 { get; set; }
        public string? IssRev2Noise { get; set; }
        public string? IssRev2Rate { get; set; }
        public string? IssRev2 { get; set; }
        public string? IssRev3Noise { get; set; }
        public string? IssRev3Rate { get; set; }
        public string? IssRev3 { get; set; }
        public string? IssRev4Noise { get; set; }
        public string? IssRev4Rate { get; set; }
        public string? IssRev4 { get; set; }
        public string? IssRev5Noise { get; set; }
        public string? IssRev5Rate { get; set; }
        public string? IssRev5 { get; set; }
        public string? IssRevLast1Noise { get; set; }
        public string? IssRevLast1Rate { get; set; }
        public string? IssRevLast1 { get; set; }
        public string? IssRevLast2Noise { get; set; }
        public string? IssRevLast2Rate { get; set; }
        public string? IssRevLast2 { get; set; }
        public string? IssRevLast3Noise { get; set; }
        public string? IssRevLast3Rate { get; set; }
        public string? IssRevLast3 { get; set; }
        public string? IssRevLast4Noise { get; set; }
        public string? IssRevLast4Rate { get; set; }
        public string? IssRevLast4 { get; set; }
        public string? IssRevLast5Noise { get; set; }
        public string? IssRevLast5Rate { get; set; }
        public string? IssRevLast5 { get; set; }
        public string? IssSlow1Noise { get; set; }
        public string? IssSlow1Rate { get; set; }
        public string? IssSlow1 { get; set; }
        public string? IssSlow2Noise { get; set; }
        public string? IssSlow2Rate { get; set; }
        public string? IssSlow2 { get; set; }
        public string? IssSlow3Noise { get; set; }
        public string? IssSlow3Rate { get; set; }
        public string? IssSlow3 { get; set; }
        public string? IssSlow4Noise { get; set; }
        public string? IssSlow4Rate { get; set; }
        public string? IssSlow4 { get; set; }
        public string? IssSlow5Noise { get; set; }
        public string? IssSlow5Rate { get; set; }
        public string? IssSlow5 { get; set; }
        public string? IssSlowLast1Noise { get; set; }
        public string? IssSlowLast1Rate { get; set; }
        public string? IssSlowLast1 { get; set; }
        public string? IssSlowLast2Noise { get; set; }
        public string? IssSlowLast2Rate { get; set; }
        public string? IssSlowLast2 { get; set; }
        public string? IssSlowLast3Noise { get; set; }
        public string? IssSlowLast3Rate { get; set; }
        public string? IssSlowLast3 { get; set; }
        public string? IssSlowLast4Noise { get; set; }
        public string? IssSlowLast4Rate { get; set; }
        public string? IssSlowLast4 { get; set; }
        public string? IssSlowLast5Noise { get; set; }
        public string? IssSlowLast5Rate { get; set; }
        public string? IssSlowLast5 { get; set; }
        public string? IssRevColor { get; set; }
        public string? IssSlowColor { get; set; }
        public string? IssRevColor1dB { get; set; }
        public string? IssRevColor1Hz { get; set; }
        public string? IssRevColor1rpm { get; set; }
        public string? IssRevColor1sum { get; set; }
        public string? IssRevColor1Dec { get; set; }
        public string? IssSlowColor1dB { get; set; }
        public string? IssSlowColor1Hz { get; set; }
        public string? IssSlowColor1rpm { get; set; }
        public string? IssSlowColor1sum { get; set; }
        public string? IssSlowColor1Dec { get; set; }
        public string? IssRevColor2dB { get; set; }
        public string? IssRevColor2Hz { get; set; }
        public string? IssRevColor2rpm { get; set; }
        public string? IssRevColor2sum { get; set; }
        public string? IssRevColor2Dec { get; set; }
        public string? IssSlowColor2dB { get; set; }
        public string? IssSlowColor2Hz { get; set; }
        public string? IssSlowColor2rpm { get; set; }
        public string? IssSlowColor2sum { get; set; }
        public string? IssSlowColor2Dec { get; set; }
        public string? IssRevColor3dB { get; set; }
        public string? IssRevColor3Hz { get; set; }
        public string? IssRevColor3rpm { get; set; }
        public string? IssRevColor3sum { get; set; }
        public string? IssRevColor3Dec { get; set; }
        public string? IssSlowColor3dB { get; set; }
        public string? IssSlowColor3Hz { get; set; }
        public string? IssSlowColor3rpm { get; set; }
        public string? IssSlowColor3sum { get; set; }
        public string? IssSlowColor3Dec { get; set; }
        public string? IssCol { get; set; }
        public string? IssOilPump { get; set; }
        public string? IssOilPumpDec { get; set; }
        public string? IssReliefValve { get; set; }
        public string? IssReliefValveDec { get; set; }
        public string? PokayokeDate26 { get; set; }
        public string? PokayokeDate28 { get; set; }
        public string? PokayokeDate29 { get; set; }
        public string? EngravingData { get; set; }
        public string? PokayokeDate30 { get; set; }
        public string? PokayokeDate31 { get; set; }
        public string? InspectionDate { get; set; }
        public string? PokayokeDate32 { get; set; }
        public string? HsgSetDate { get; set; }
        public string? Tray { get; set; }
        public string? Weight { get; set; }
        public DateTime? CollectionDate { get; set; }
        public int? Number { get; set; }
    }
}
