using System;
using System.Collections.Generic;

namespace Traceability_System.Entity.Models
{
    public partial class Vw1RotorTable
    {
        public string? Ro1Mg1rserial { get; set; }
        public string? Ro1RotorShaftTrans { get; set; }
        public string? Ro1RotorCoreTrans { get; set; }
        public string? Ro1RotorHeating { get; set; }
        public string? Ro1RotorShaftPress { get; set; }
        public string? Ro1RotorNutTight { get; set; }
        public string? Ro1RotorForeignSuction { get; set; }
        public string? Ro1RotorNutCrimpMg1press { get; set; }
        public string? Ro1RotorResolverPress { get; set; }
        public string? Ro1RotorReject { get; set; }
        public string? Ro1RotorMagnetization { get; set; }
        public string? Ro1RotorExtractionInsp { get; set; }
        public string? Ro1RotorShippingInsp { get; set; }
        public string? Ro1RotorTamg2shaftTrans { get; set; }
        public string? Ro1RotorTamg2coreTrans { get; set; }
        public string? Ro1RotorTamg2heating { get; set; }
        public string? Ro1RotorTamg2shaftPress { get; set; }
        public string? Ro1RotorTamg2nutTight { get; set; }
        public string? Ro1RotorTamg2foreignSuction { get; set; }
        public string? Ro1RotorTamg2nutCrimpMg1press { get; set; }
        public string? Ro1RotorTamg2resolverPress { get; set; }
        public string? Ro1RotorTamg2reject { get; set; }
        public string? Ro1RotorTamg2magnetization { get; set; }
        public string? Ro1RotorTamg2extractionInsp { get; set; }
        public string? Ro1RotorTamg2shippingInsp { get; set; }
        public string? Ro1MotorMtrCode { get; set; }
        public string? Ro1MotorSngen { get; set; }
        public string? Ro1MotorHsgSrfBrgAm { get; set; }
        public string? Ro1MotorHsgSrfKnockPam { get; set; }
        public string? Ro1MotorCoolPipeMw { get; set; }
        public string? Ro1MotorTermBoardMw { get; set; }
        public string? Ro1MotorRrCoverSrfOutBrgAm { get; set; }
        public string? Ro1MotorRrCoverSrfKnockPam { get; set; }
        public string? Ro1MotorMg1statorInsAm { get; set; }
        public string? Ro1MotorMg2statorInsAm { get; set; }
        public string? Ro1MotorHarnEscMw { get; set; }
        public string? Ro1MotorMg12statorTightAm { get; set; }
        public string? Ro1MotorThermMw { get; set; }
        public string? Ro1MotorCoolPipeMw2 { get; set; }
        public string? Ro1MotorMg12rotorAssem { get; set; }
        public string? Ro1MotorFipgapp { get; set; }
        public string? Ro1MotorRrCoverAssem { get; set; }
        public string? Ro1MotorRrCoverTight1 { get; set; }
        public string? Ro1MotorRrCoverTight2 { get; set; }
        public string? Ro1MotorInvMw { get; set; }
        public string? Ro1MotorMw1 { get; set; }
        public string? Ro1MotorMw2 { get; set; }
        public string? Ro1MotorPrevStn { get; set; }
        public string? Ro1MotorMwco0 { get; set; }
        public string? Ro1MotorMwco1 { get; set; }
        public string? Ro1MotorMwco2 { get; set; }
        public string? Ro1MotorMwco3 { get; set; }
        public string? Ro1MotorReject { get; set; }
        public string? Ro1CoverSubIdsetSpare { get; set; }
        public string? Ro1CoverSubRrCovSetDmread { get; set; }
        public string? Ro1CoverSubRrCovBrgPressEquip { get; set; }
        public string? Ro1CoverSubMw1 { get; set; }
        public string? Ro1CoverSubMw2 { get; set; }
        public string? Ro1CoverSubMw3 { get; set; }
        public string? Ro1CoverSubMw4 { get; set; }
        public string? Ro1CoverSubRrRevEquip { get; set; }
        public string? Ro1CoverSubWaterConnTighten { get; set; }
        public string? Ro1CoverSubReject { get; set; }
        public string? Ro1DefDfcaseRead { get; set; }
        public string? Ro1DefDfpinionShaftEquip { get; set; }
        public string? Ro1DefDiffOperMeasureEquip { get; set; }
        public string? Ro1DefTweezersMw { get; set; }
        public string? Ro1DefDiffPinionPress { get; set; }
        public string? Ro1Dmread { get; set; }
        public string? Ro1GearPressIn1 { get; set; }
        public string? Ro1GearPressIn2 { get; set; }
        public string? Ro1Slnffastening { get; set; }
        public string? Ro1Slnfriveting { get; set; }
        public string? Ro1DiffBrgPressIn { get; set; }
        public string? Ro1DiffBoltTight1 { get; set; }
        public string? Ro1DiffBoltTight2 { get; set; }
        public string? Ro1RevRivetConfirm { get; set; }
        public string? Ro1DamperImage { get; set; }
        public string? Ro1PokayokeDate39 { get; set; }
        public string? Ro1PokayokeDate40 { get; set; }
        public string? Ro1HsgBrgMeasDate { get; set; }
        public string? Ro1HsgBrgInflectPtStroke { get; set; }
        public string? Ro1HsgBrgInflectPtLoad { get; set; }
        public string? Ro1HsgBrgFinalStroke { get; set; }
        public string? Ro1HsgBrgFinalLoad { get; set; }
        public string? Ro1HsgBrgInflectPtStrokeSec { get; set; }
        public string? Ro1HsgBrgInflectPtLoadSec { get; set; }
        public string? Ro1HsgBrgFinalStrokeSec { get; set; }
        public string? Ro1HsgBrgFinalLoadSec { get; set; }
        public string? Ro1HsgBrgMaasterStroke { get; set; }
        public string? Ro1PokayokeDate41 { get; set; }
        public string? Ro1PokayokeDate42 { get; set; }
        public string? Ro1PokayokeDate43 { get; set; }
        public string? Ro1PokayokeDate44 { get; set; }
        public string? Ro1UpenderDate { get; set; }
        public string? Ro1PokayokeDate45 { get; set; }
        public string? Ro1RejectTimeDate { get; set; }
        public string? Ro1PokayokeDate33 { get; set; }
        public string? Ro1DgameasDate { get; set; }
        public string? Ro1Dgapos3Axis { get; set; }
        public string? Ro1Dgaload3Axis { get; set; }
        public string? Ro1Dgapos4Axis { get; set; }
        public string? Ro1Dgaload4Axis { get; set; }
        public string? Ro1PokayokeDate34 { get; set; }
        public string? Ro1DgmmeasTimeDate { get; set; }
        public string? Ro1Dgmdagjudge { get; set; }
        public string? Ro1DgmlhRh { get; set; }
        public string? Ro1DgmmaxTorque { get; set; }
        public string? Ro1DgmminTorque { get; set; }
        public string? Ro1DprmeasTimeDate { get; set; }
        public string? Ro1Dprfrs { get; set; }
        public string? Ro1Dprfrl { get; set; }
        public string? Ro1PokayokeDate35 { get; set; }
        public string? Ro1GearMeasDate { get; set; }
        public string? Ro1GearStroke { get; set; }
        public string? Ro1GearLoad { get; set; }
        public string? Ro1GearFinalStroke { get; set; }
        public string? Ro1GearFinalLoad { get; set; }
        public string? Ro1GearStrokeSec { get; set; }
        public string? Ro1GearLoadSec { get; set; }
        public string? Ro1GearFinalStrokeSec { get; set; }
        public string? Ro1GearFinalLoadSec { get; set; }
        public string? Ro1GearMainStroke { get; set; }
        public string? Ro1GearAbvalue { get; set; }
        public string? Ro1Gear2Date { get; set; }
        public string? Ro1Gear2Stroke { get; set; }
        public string? Ro1Gear2Load { get; set; }
        public string? Ro1Gear2FinalStroke { get; set; }
        public string? Ro1Gear2FinalLoad { get; set; }
        public string? Ro1Gear2StrokeSec { get; set; }
        public string? Ro1Gear2LoadSec { get; set; }
        public string? Ro1Gear2FinalStrokeSec { get; set; }
        public string? Ro1Gear2FinalLoadSec { get; set; }
        public string? Ro1Gear2MainStroke { get; set; }
        public string? Ro1Gear2Abvalue { get; set; }
        public string? Ro1DpntDate { get; set; }
        public string? Ro1DpntTorqueAxis1 { get; set; }
        public string? Ro1DpntAngleAxis1 { get; set; }
        public string? Ro1DpntJudgment { get; set; }
        public string? Ro1DpntSeating { get; set; }
        public string? Ro1DpntDrop { get; set; }
        public string? Ro1DpntSlack { get; set; }
        public string? Ro1DpnfMeasDate { get; set; }
        public string? Ro1DpnfFinalStroke { get; set; }
        public string? Ro1DpnfFinalLoad { get; set; }
        public string? Ro1DpnfMainStroke { get; set; }
        public string? Ro1DfbrgDate { get; set; }
        public string? Ro1Dfbrgstroke { get; set; }
        public string? Ro1Dfbrgload { get; set; }
        public string? Ro1DfbrgfinalStroke { get; set; }
        public string? Ro1DfbrgfinalLoad { get; set; }
        public string? Ro1DfbrgstrokeSec { get; set; }
        public string? Ro1DfbrgloadSec { get; set; }
        public string? Ro1DfbrgfinalStrokeSec { get; set; }
        public string? Ro1DfbrgfinalLoadSec { get; set; }
        public string? Ro1DfbrgmainStroke { get; set; }
        public string? Ro1Df1Date { get; set; }
        public string? Ro1Df1angleAxis1 { get; set; }
        public string? Ro1Df1codeAxis1 { get; set; }
        public string? Ro1Df1angleAxis2 { get; set; }
        public string? Ro1Df1codeAxis2 { get; set; }
        public string? Ro1Df1angleAxis3 { get; set; }
        public string? Ro1Df1codeAxis3 { get; set; }
        public string? Ro1Df1angleAxis4 { get; set; }
        public string? Ro1Df1codeAxis4 { get; set; }
        public string? Ro1Df1angleAxis5 { get; set; }
        public string? Ro1Df1codeAxis5 { get; set; }
        public string? Ro1Df1angleAxis6 { get; set; }
        public string? Ro1Df1codeAxis6 { get; set; }
        public string? Ro1Df1abvalue { get; set; }
        public string? Ro1Df2Date { get; set; }
        public string? Ro1Df2angleAxis1 { get; set; }
        public string? Ro1Df2codeAxis1 { get; set; }
        public string? Ro1Df2angleAxis2 { get; set; }
        public string? Ro1Df2codeAxis2 { get; set; }
        public string? Ro1Df2angleAxis3 { get; set; }
        public string? Ro1Df2codeAxis3 { get; set; }
        public string? Ro1Df2angleAxis4 { get; set; }
        public string? Ro1Df2codeAxis4 { get; set; }
        public string? Ro1Df2angleAxis5 { get; set; }
        public string? Ro1Df2codeAxis5 { get; set; }
        public string? Ro1Df2angleAxis6 { get; set; }
        public string? Ro1Df2codeAxis6 { get; set; }
        public string? Ro1Df2abvalue { get; set; }
        public string? Ro1DfreverseDate { get; set; }
        public string? Ro1PokayokeDate36 { get; set; }
        public string? Ro1PokayokeDate37 { get; set; }
        public string? Ro1PokayokeDate38 { get; set; }
        public string? Ro1Mg1workTemp { get; set; }
        public string? Ro1Mg1fluxValue { get; set; }
        public string? Ro1Mg1dec { get; set; }
        public string? Ro1Mg2workTemp { get; set; }
        public string? Ro1Mg2fluxValue { get; set; }
        public string? Ro1Mg2dec { get; set; }
        public string? Ro1AslDate { get; set; }
        public string? Ro1IctlDate { get; set; }
        public string? Ro1Rcserial { get; set; }
        public string? Ro1AxisSerial { get; set; }
        public string? Ro1ProcDate { get; set; }
        public string? Ro1IsRcheat { get; set; }
        public string? Ro1HeatSt { get; set; }
        public string? Ro1HeatProcedure { get; set; }
        public string? Ro1RoomTemp { get; set; }
        public string? Ro1AxisTemp { get; set; }
        public string? Ro1CoreBefore { get; set; }
        public string? Ro1CoreAfter { get; set; }
        public string? Ro1Ihbefore { get; set; }
        public string? Ro1Ihafter { get; set; }
        public string? Ro1Cdtemp { get; set; }
        public string? Ro1HeatTime { get; set; }
        public string? Ro1HeatOutput { get; set; }
        public string? Ro1HeatEndTime { get; set; }
        public string? Ro1JudgmentCode { get; set; }
        public string? Ro1ApiDate { get; set; }
        public string? Ro1Apistroke { get; set; }
        public string? Ro1Apiload { get; set; }
        public string? Ro1ApifinalStroke { get; set; }
        public string? Ro1ApimainStroke { get; set; }
        public string? Ro1ApicoreTemp { get; set; }
        public string? Ro1Apisttime { get; set; }
        public string? Ro1ApiinitTilt { get; set; }
        public string? Ro1Apipos { get; set; }
        public string? Ro1ApideviationLoad { get; set; }
        public string? Ro1Apicode { get; set; }
        public string? Ro1Apimachine { get; set; }
        public string? Ro1NtDate { get; set; }
        public string? Ro1NttorqueAxis1 { get; set; }
        public string? Ro1NtangleAxis1 { get; set; }
        public string? Ro1Ntcode { get; set; }
        public string? Ro1Nthistory { get; set; }
        public string? Ro1Ntseating1 { get; set; }
        public string? Ro1Ntdrop1 { get; set; }
        public string? Ro1Ntslack1 { get; set; }
        public string? Ro1RapDate { get; set; }
        public string? Ro1Rapbefore { get; set; }
        public string? Ro1Rapafter { get; set; }
        public string? Ro1Rapload { get; set; }
        public string? Ro1RapmainStroke { get; set; }
        public string? Ro1Rapcode { get; set; }
        public string? Ro1RapwashSensor { get; set; }
        public string? Ro1RapwashMain { get; set; }
        public string? Ro1RapwashPos { get; set; }
        public string? Ro1Rapstroke { get; set; }
        public string? Ro1RaploadSec { get; set; }
        public string? Ro1RapfinalStroke { get; set; }
        public string? Ro1Rapmain2Stroke { get; set; }
        public string? Ro1Rapcode2 { get; set; }
        public string? Ro1RtpstartDate { get; set; }
        public string? Ro1Rtpstroke { get; set; }
        public string? Ro1Rtpload { get; set; }
        public string? Ro1RtpfinalStroke { get; set; }
        public string? Ro1RtpmainStroke { get; set; }
        public string? Ro1Rtpcode { get; set; }
        public string? Ro1Rtphistory { get; set; }
        public string? Ro1Detection1 { get; set; }
        public string? Ro1Detection2 { get; set; }
        public DateTime? Ro1CollectionDate { get; set; }
    }
}
