using System;
using System.Collections.Generic;

namespace Traceability_System.Entity.Models
{
    public partial class VwMotorTable
    {
        public string? MoShipmentSerial { get; set; }
        public string? MoRotorShaftTrans { get; set; }
        public string? MoRotorCoreTrans { get; set; }
        public string? MoRotorHeating { get; set; }
        public string? MoRotorShaftPress { get; set; }
        public string? MoRotorNutTight { get; set; }
        public string? MoRotorForeignSuction { get; set; }
        public string? MoRotorNutCrimpMg1press { get; set; }
        public string? MoRotorResolverPress { get; set; }
        public string? MoRotorReject { get; set; }
        public string? MoRotorMagnetization { get; set; }
        public string? MoRotorExtractionInsp { get; set; }
        public string? MoRotorShippingInsp { get; set; }
        public string? MoRotorTamg2shaftTrans { get; set; }
        public string? MoRotorTamg2coreTrans { get; set; }
        public string? MoRotorTamg2heating { get; set; }
        public string? MoRotorTamg2shaftPress { get; set; }
        public string? MoRotorTamg2nutTight { get; set; }
        public string? MoRotorTamg2foreignSuction { get; set; }
        public string? MoRotorTamg2nutCrimpMg1press { get; set; }
        public string? MoRotorTamg2resolverPress { get; set; }
        public string? MoRotorTamg2reject { get; set; }
        public string? MoRotorTamg2magnetization { get; set; }
        public string? MoRotorTamg2extractionInsp { get; set; }
        public string? MoRotorTamg2shippingInsp { get; set; }
        public string? MoPokayokeDate1 { get; set; }
        public string? MoPokayokeDate2 { get; set; }
        public string? MoHsgBrgDate { get; set; }
        public string? MoHsgBrgStroke { get; set; }
        public string? MoHsgBrgLoad { get; set; }
        public string? MoHsgBrgFinalStroke { get; set; }
        public string? MoHsgBrgFinalLoad { get; set; }
        public string? MoHsgBrgStrokeSec { get; set; }
        public string? MoHsgBrgLoadSec { get; set; }
        public string? MoHsgBrgFinalStrokeSec { get; set; }
        public string? MoHsgBrgFinalLoadSec { get; set; }
        public string? MoHsgBrgMainStroke { get; set; }
        public string? MoHsgBrgAbvalue { get; set; }
        public string? MoHsgKnockDate { get; set; }
        public string? MoHsgKnockStroke { get; set; }
        public string? MoHsgKnockLoad { get; set; }
        public string? MoHsgKnockFinalStroke { get; set; }
        public string? MoHsgKnockFinalLoad { get; set; }
        public string? MoHsgKnockStrokeSec { get; set; }
        public string? MoHsgKnockLoadSec { get; set; }
        public string? MoHsgKnockFinalStrokeSec { get; set; }
        public string? MoHsgKnockFinalLoadSec { get; set; }
        public string? MoHsgKnockMainStroke { get; set; }
        public string? MoHsgKnockAbvalue { get; set; }
        public string? MoPokayokeDate3 { get; set; }
        public string? MoPokayokeDate4 { get; set; }
        public string? MoRrbrgDate { get; set; }
        public string? MoRrbrgStroke { get; set; }
        public string? MoRrbrgLoad { get; set; }
        public string? MoRrbrgFinalStroke { get; set; }
        public string? MoRrbrgFinalLoad { get; set; }
        public string? MoRrbrgStrokeSec { get; set; }
        public string? MoRrbrgLoadSec { get; set; }
        public string? MoRrbrgFinalStrokeSec { get; set; }
        public string? MoRrbrgFinalLoadSec { get; set; }
        public string? MoRrbrgMainStroke { get; set; }
        public string? MoRrbrgAbvalue { get; set; }
        public string? MoRrknockDate { get; set; }
        public string? MoRrknockStroke { get; set; }
        public string? MoRrknockLoad { get; set; }
        public string? MoRrknockFinalStroke { get; set; }
        public string? MoRrknockFinalLoad { get; set; }
        public string? MoRrknockStrokeSec { get; set; }
        public string? MoRrknockLoadSec { get; set; }
        public string? MoRrknockFinalStrokeSec { get; set; }
        public string? MoRrknockFinalLoadSec { get; set; }
        public string? MoRrknockMainStroke { get; set; }
        public string? MoRrknockAbvalue { get; set; }
        public string? MoMg1date { get; set; }
        public string? MoMg1torqAngleAxis1 { get; set; }
        public string? MoMg1codeAxis1 { get; set; }
        public string? MoMg1torqAngleAxis2 { get; set; }
        public string? MoMg1codeAxis2 { get; set; }
        public string? MoMg1torqAngleAxis3 { get; set; }
        public string? MoMg1codeAxis3 { get; set; }
        public string? MoMg2date { get; set; }
        public string? MoMg2torqAngleAxis1 { get; set; }
        public string? MoMg2codeAxis1 { get; set; }
        public string? MoMg2torqAngleAxis2 { get; set; }
        public string? MoMg2codeAxis2 { get; set; }
        public string? MoMg2torqAngleAxis3 { get; set; }
        public string? MoMg2codeAxis3 { get; set; }
        public string? MoPokayokeDate5 { get; set; }
        public string? MoStatorDate { get; set; }
        public string? MoTorqAngleAxis1 { get; set; }
        public string? MoCodeAxis1 { get; set; }
        public string? MoTorqAngleAxis2 { get; set; }
        public string? MoCodeAxis2 { get; set; }
        public string? MoTorqAngleAxis3 { get; set; }
        public string? MoCodeAxis3 { get; set; }
        public string? MoAngleAxis1Sec { get; set; }
        public string? MoAxisCode1Sec { get; set; }
        public string? MoAngleAxis2Sec { get; set; }
        public string? MoAxisCode2Sec { get; set; }
        public string? MoAngleAxis3Sec { get; set; }
        public string? MoAxisCode3Sec { get; set; }
        public string? MoMg1stator1 { get; set; }
        public string? MoMg1stator2 { get; set; }
        public string? MoMg1stator3 { get; set; }
        public string? MoMg2stator1 { get; set; }
        public string? MoMg2stator2 { get; set; }
        public string? MoMg2stator3 { get; set; }
        public string? MoPokayokeDate6 { get; set; }
        public string? MoPokayokeDate7 { get; set; }
        public string? MoMeasDate { get; set; }
        public string? MoMg1workTemp { get; set; }
        public string? MoMg1fluxValue { get; set; }
        public string? MoMg1dec { get; set; }
        public string? MoMg2workTemp { get; set; }
        public string? MoMg2fluxValue { get; set; }
        public string? MoMg2dec { get; set; }
        public string? MoRrFigpdate { get; set; }
        public string? MoImgResult { get; set; }
        public string? MoRrcoverDate { get; set; }
        public string? MoTotalDate1 { get; set; }
        public string? MoTotal1AngleAxis1 { get; set; }
        public string? MoTotal1Axis1Code { get; set; }
        public string? MoTotal1AngleAxis2 { get; set; }
        public string? MoTotal1Axis2Code { get; set; }
        public string? MoTotal1AngleAxis3 { get; set; }
        public string? MoTotal1Axis3Code { get; set; }
        public string? MoTotal1AngleAxis4 { get; set; }
        public string? MoTotal1Axis4Code { get; set; }
        public string? MoTotal1AngleAxis5 { get; set; }
        public string? MoTotal1Axis5Code { get; set; }
        public string? MoTotal1AngleAxis6 { get; set; }
        public string? MoTotal1Axis6Code { get; set; }
        public string? MoTotal1AngleAxis7 { get; set; }
        public string? MoTotal1Axis7Code { get; set; }
        public string? MoTotal1AngleAxis8 { get; set; }
        public string? MoTotal1Axis8Code { get; set; }
        public string? MoTotal1AngleAxis9 { get; set; }
        public string? MoTotal1Axis9Code { get; set; }
        public string? MoTotal1AngleAxis10 { get; set; }
        public string? MoTotal1Axis10Code { get; set; }
        public string? MoTotal1AngleAxis11 { get; set; }
        public string? MoTotal1Axis11Code { get; set; }
        public string? MoTotal1Abvalue { get; set; }
        public string? MoTotal2Date { get; set; }
        public string? MoAngle1Axis { get; set; }
        public string? MoAxis1Code { get; set; }
        public string? MoAngle2Axis { get; set; }
        public string? MoAxis2Code { get; set; }
        public string? MoAngle3Axis { get; set; }
        public string? MoAxis3Code { get; set; }
        public string? MoAngle4Axis { get; set; }
        public string? MoAxis4Code { get; set; }
        public string? MoAngle5Axis { get; set; }
        public string? MoAxis5Code { get; set; }
        public string? MoAngle6Axis { get; set; }
        public string? MoAxis6Code { get; set; }
        public string? MoAngle7Axis { get; set; }
        public string? MoAxis7Code { get; set; }
        public string? MoAngle8Axis { get; set; }
        public string? MoAxis8Code { get; set; }
        public string? MoAngle9Axis { get; set; }
        public string? MoAxis9Code { get; set; }
        public string? MoAngle10Axis { get; set; }
        public string? MoAxis10Code { get; set; }
        public string? MoReDate { get; set; }
        public string? MoPokayokeDateBas { get; set; }
        public string? MoPokayokeDate8 { get; set; }
        public string? MoPokayokeDate9 { get; set; }
        public string? MoPokayokeDate10 { get; set; }
        public string? MoPokayokeDate11 { get; set; }
        public string? MoPokayokeDate12 { get; set; }
        public string? MoPokayokeDate13 { get; set; }
        public string? MoPokayokeDate14 { get; set; }
        public DateTime? MoCollectionDate { get; set; }
    }
}
