namespace Traceability_System.Entity.Models
{
    public partial class VwRrtable
    {
        public string? RrrrcoverSerial { get; set; }
        public string? RrrotorShaftTrans { get; set; }
        public string? RrrotorCoreTrans { get; set; }
        public string? RrrotorHeating { get; set; }
        public string? RrrotorShaftPress { get; set; }
        public string? RrrotorNutTight { get; set; }
        public string? RrrotorForeignSuction { get; set; }
        public string? RrrotorNutCrimpMg1press { get; set; }
        public string? RrrotorResolverPress { get; set; }
        public string? RrrotorReject { get; set; }
        public string? RrrotorMagnetization { get; set; }
        public string? RrrotorExtractionInsp { get; set; }
        public string? RrrotorShippingInsp { get; set; }
        public string? RrrotorTamg2shaftTrans { get; set; }
        public string? RrrotorTamg2coreTrans { get; set; }
        public string? RrrotorTamg2heating { get; set; }
        public string? RrrotorTamg2shaftPress { get; set; }
        public string? RrrotorTamg2nutTight { get; set; }
        public string? RrrotorTamg2foreignSuction { get; set; }
        public string? RrrotorTamg2nutCrimpMg1press { get; set; }
        public string? RrrotorTamg2resolverPress { get; set; }
        public string? RrrotorTamg2reject { get; set; }
        public string? RrrotorTamg2magnetization { get; set; }
        public string? RrrotorTamg2extractionInsp { get; set; }
        public string? RrrotorTamg2shippingInsp { get; set; }
        public string? RrmotorMtrCode { get; set; }
        public string? RrmotorSngen { get; set; }
        public string? RrmotorHsgSrfBrgAm { get; set; }
        public string? RrmotorHsgSrfKnockPam { get; set; }
        public string? RrmotorCoolPipeMw { get; set; }
        public string? RrmotorTermBoardMw { get; set; }
        public string? RrmotorRrCoverSrfOutBrgAm { get; set; }
        public string? RrmotorRrCoverSrfKnockPam { get; set; }
        public string? RrmotorMg1statorInsAm { get; set; }
        public string? RrmotorMg2statorInsAm { get; set; }
        public string? RrmotorHarnEscMw { get; set; }
        public string? RrmotorMg12statorTightAm { get; set; }
        public string? RrmotorThermMw { get; set; }
        public string? RrmotorCoolPipeMw2 { get; set; }
        public string? RrmotorMg12rotorAssem { get; set; }
        public string? RrmotorFipgapp { get; set; }
        public string? RrmotorRrCoverAssem { get; set; }
        public string? RrmotorRrCoverTight1 { get; set; }
        public string? RrmotorRrCoverTight2 { get; set; }
        public string? RrmotorInvMw { get; set; }
        public string? RrmotorMw1 { get; set; }
        public string? RrmotorMw2 { get; set; }
        public string? RrmotorPrevStn { get; set; }
        public string? RrmotorMwco0 { get; set; }
        public string? RrmotorMwco1 { get; set; }
        public string? RrmotorMwco2 { get; set; }
        public string? RrmotorMwco3 { get; set; }
        public string? RrmotorReject { get; set; }
        public string? RrcoverSubIdsetSpare { get; set; }
        public string? RrcoverSubRrCovSetDmread { get; set; }
        public string? RrcoverSubRrCovBrgPressEquip { get; set; }
        public string? RrcoverSubMw1 { get; set; }
        public string? RrcoverSubMw2 { get; set; }
        public string? RrcoverSubMw3 { get; set; }
        public string? RrcoverSubMw4 { get; set; }
        public string? RrcoverSubRrRevEquip { get; set; }
        public string? RrcoverSubWaterConnTighten { get; set; }
        public string? RrcoverSubReject { get; set; }
        public string? RrdefDfcaseRead { get; set; }
        public string? RrdefDfpinionShaftEquip { get; set; }
        public string? RrdefDiffOperMeasureEquip { get; set; }
        public string? RrdefTweezersMw { get; set; }
        public string? RrdefDiffPinionPress { get; set; }
        public string? Rrdmread { get; set; }
        public string? RrgearPressIn1 { get; set; }
        public string? RrgearPressIn2 { get; set; }
        public string? Rrslnffastening { get; set; }
        public string? Rrslnfriveting { get; set; }
        public string? RrdiffBrgPressIn { get; set; }
        public string? RrdiffBoltTight1 { get; set; }
        public string? RrdiffBoltTight2 { get; set; }
        public string? RrrevRivetConfirm { get; set; }
        public string? RrdamperImage { get; set; }
        public string? RrpokayokeDate39 { get; set; }
        public string? RrpokayokeDate40 { get; set; }
        public string? RrhsgBrgMdate { get; set; }
        public string? RrhsgBrgStroke { get; set; }
        public string? RrhsgBrgLoad { get; set; }
        public string? RrhsgBrgFinalStroke { get; set; }
        public string? RrhsgBrgFinalLoad { get; set; }
        public string? RrhsgBrgStrokeSec { get; set; }
        public string? RrhsgBrgLoadSec { get; set; }
        public string? RrhsgBrgFinalStrokeSec { get; set; }
        public string? RrhsgBrgFinalLoadSec { get; set; }
        public string? RrhsgBrgMainStroke { get; set; }
        public string? RrpokayokeDate41 { get; set; }
        public string? RrpokayokeDate42 { get; set; }
        public string? RrpokayokeDate43 { get; set; }
        public string? RrpokayokeDate44 { get; set; }
        public string? RrupenderDate { get; set; }
        public string? RrpokayokeDate45 { get; set; }
        public string? RrrejectTimeDate { get; set; }
        public DateTime? RrcollectionDate { get; set; }
    }
}
